import type { ToolGatewayCatalogEntry } from "@opengeni/contracts";
import { compareCanonicalStrings, parseVerifiedToolGatewayCatalog } from "./catalog";
import { ToolGatewayPathCollisionError } from "./errors";

export type GenerateToolGatewayDeclarationsOptions = {
  moduleSpecifier?: string;
  interfaceName?: string;
};

type NamespaceNode = {
  children: Map<string, NamespaceNode>;
  entry: ToolGatewayCatalogEntry | null;
};

/** Generate declaration merging for one exact digest-pinned workspace catalog. */
export function generateToolGatewayDeclarations(
  catalog: Parameters<typeof parseVerifiedToolGatewayCatalog>[0],
  options: GenerateToolGatewayDeclarationsOptions = {},
): string {
  const verified = parseVerifiedToolGatewayCatalog(catalog);
  return generateToolDeclarations(
    { digest: verified.digest, entries: verified.entries },
    {
      moduleSpecifier: options.moduleSpecifier ?? "@opengeni/sdk",
      interfaceName: options.interfaceName ?? "OpenGeniGeneratedTools",
      callOptionsType: "OpenGeniToolCallOptions",
      fallbackResultType: "ToolGatewayResult",
      generatedBy: "@opengeni/tool-gateway",
      catalogDigestLabel: "Tool catalog digest",
    },
  );
}

export function generateToolDeclarations(
  catalog: { digest: string; entries: readonly ToolGatewayCatalogEntry[] },
  options: {
    moduleSpecifier: string;
    interfaceName: string;
    callOptionsType: string;
    fallbackResultType: string;
    generatedBy: string;
    catalogDigestLabel?: string;
  },
): string {
  const root = namespaceNode();
  for (const entry of catalog.entries) insertEntry(root, entry);
  return [
    `// Generated by ${options.generatedBy}. Do not edit.`,
    `// ${options.catalogDigestLabel ?? "Tool catalog digest"}: ${catalog.digest}`,
    `import type { ${options.callOptionsType}, ${options.fallbackResultType} } from ${JSON.stringify(options.moduleSpecifier)};`,
    "",
    `declare module ${JSON.stringify(options.moduleSpecifier)} {`,
    `  interface ${options.interfaceName} {`,
    ...renderChildren(root, 4, options),
    "  }",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

/** Honest bounded JSON-Schema-to-TypeScript projection for generated declarations. */
export function jsonSchemaToTypeScript(schema: unknown): string {
  return schemaType(schema, schema, new Set(), 0);
}

function namespaceNode(): NamespaceNode {
  return { children: new Map(), entry: null };
}

function insertEntry(root: NamespaceNode, entry: ToolGatewayCatalogEntry): void {
  let node = root;
  for (const [index, segment] of entry.codemodePath.entries()) {
    if (node.entry) {
      throw new ToolGatewayPathCollisionError(entry.codemodePath, "extends_leaf");
    }
    let child = node.children.get(segment);
    if (!child) {
      child = namespaceNode();
      node.children.set(segment, child);
    }
    node = child;
    if (index === entry.codemodePath.length - 1) {
      if (node.entry || node.children.size > 0) {
        throw new ToolGatewayPathCollisionError(entry.codemodePath, "collision");
      }
      node.entry = entry;
    }
  }
}

function renderChildren(
  node: NamespaceNode,
  indent: number,
  options: Parameters<typeof generateToolDeclarations>[1],
): string[] {
  const lines: string[] = [];
  for (const [name, child] of [...node.children].sort(([left], [right]) =>
    compareCanonicalStrings(left, right),
  )) {
    if (child.entry) {
      const entry = child.entry;
      const input = jsonSchemaToTypeScript(entry.inputSchema);
      const output = entry.outputSchema
        ? jsonSchemaToTypeScript(entry.outputSchema)
        : options.fallbackResultType;
      const description = boundedDoc(entry.description ?? entry.title);
      if (description) lines.push(...renderDoc(description, indent));
      lines.push(`${spaces(indent)}readonly ${name}: (`);
      lines.push(
        `${spaces(indent + 2)}argumentsValue${rootObjectArgumentsAreOptional(entry.inputSchema) ? "?" : ""}: ${input},`,
      );
      lines.push(`${spaces(indent + 2)}options?: ${options.callOptionsType},`);
      lines.push(`${spaces(indent)}) => Promise<${output}>;`);
      continue;
    }
    lines.push(`${spaces(indent)}readonly ${name}: {`);
    lines.push(...renderChildren(child, indent + 2, options));
    lines.push(`${spaces(indent)}};`);
  }
  return lines;
}

function rootObjectArgumentsAreOptional(schema: unknown): boolean {
  if (!isObject(schema)) return false;
  const required = Array.isArray(schema.required)
    ? schema.required.filter((value): value is string => typeof value === "string")
    : [];
  return required.length === 0 && (schema.type === "object" || isObject(schema.properties));
}

function schemaType(schema: unknown, root: unknown, resolving: Set<string>, depth: number): string {
  if (depth > 48 || schema === true) return "unknown";
  if (schema === false) return "never";
  if (!isObject(schema)) return "unknown";
  if (typeof schema.$ref === "string") {
    if (!schema.$ref.startsWith("#/") || resolving.has(schema.$ref)) return "unknown";
    const resolved = resolveLocalReference(root, schema.$ref);
    if (resolved === undefined) return "unknown";
    const next = new Set(resolving);
    next.add(schema.$ref);
    return schemaType(resolved, root, next, depth + 1);
  }
  if (Object.hasOwn(schema, "const")) return literalType(schema.const);
  if (Array.isArray(schema.enum)) return union(schema.enum.map(literalType));
  const composites: string[] = [];
  if (Array.isArray(schema.oneOf)) {
    composites.push(
      union(schema.oneOf.map((part) => schemaType(part, root, resolving, depth + 1))),
    );
  }
  if (Array.isArray(schema.anyOf)) {
    composites.push(
      union(schema.anyOf.map((part) => schemaType(part, root, resolving, depth + 1))),
    );
  }
  if (Array.isArray(schema.allOf)) {
    composites.push(
      intersection(schema.allOf.map((part) => schemaType(part, root, resolving, depth + 1))),
    );
  }
  if (composites.length > 0) {
    const composed = intersection(composites);
    return schema.nullable === true ? union([composed, "null"]) : composed;
  }
  const types = Array.isArray(schema.type)
    ? schema.type.filter((value): value is string => typeof value === "string")
    : typeof schema.type === "string"
      ? [schema.type]
      : inferredTypes(schema);
  const rendered = types.map((type) => typeType(type, schema, root, resolving, depth + 1));
  if (schema.nullable === true) rendered.push("null");
  return union(rendered.length > 0 ? rendered : ["unknown"]);
}

function typeType(
  type: string,
  schema: Record<string, unknown>,
  root: unknown,
  resolving: Set<string>,
  depth: number,
): string {
  if (type === "null" || type === "boolean" || type === "string") return type;
  if (type === "integer" || type === "number") return "number";
  if (type === "array") return arrayType(schema, root, resolving, depth);
  if (type !== "object") return "unknown";
  return objectType(schema, root, resolving, depth);
}

function arrayType(
  schema: Record<string, unknown>,
  root: unknown,
  resolving: Set<string>,
  depth: number,
): string {
  if (Array.isArray(schema.prefixItems)) {
    const tuple = schema.prefixItems.map((item) => schemaType(item, root, resolving, depth + 1));
    if (schema.items === false) return `readonly [${tuple.join(", ")}]`;
    const rest =
      schema.items === undefined || schema.items === true
        ? "unknown"
        : schemaType(schema.items, root, resolving, depth + 1);
    return `readonly [${tuple.join(", ")}${tuple.length > 0 ? ", " : ""}...${rest}[]]`;
  }
  const item =
    schema.items === undefined || schema.items === true
      ? "unknown"
      : schemaType(schema.items, root, resolving, depth + 1);
  return `readonly (${item})[]`;
}

function objectType(
  schema: Record<string, unknown>,
  root: unknown,
  resolving: Set<string>,
  depth: number,
): string {
  const properties = isObject(schema.properties) ? schema.properties : {};
  const required = new Set(
    Array.isArray(schema.required)
      ? schema.required.filter((value): value is string => typeof value === "string")
      : [],
  );
  const entries = Object.entries(properties).sort(([left], [right]) =>
    compareCanonicalStrings(left, right),
  );
  const fields = entries.map(
    ([name, value]) =>
      `readonly ${identifierOrQuoted(name)}${required.has(name) ? "" : "?"}: ${schemaType(value, root, resolving, depth + 1)}`,
  );
  for (const missing of [...required]
    .filter((name) => !Object.hasOwn(properties, name))
    .sort(compareCanonicalStrings)) {
    fields.push(`readonly ${identifierOrQuoted(missing)}: unknown`);
  }
  if (schema.additionalProperties !== false) {
    if (
      entries.length === 0 &&
      schema.additionalProperties !== undefined &&
      schema.additionalProperties !== true
    ) {
      return `Readonly<Record<string, ${schemaType(
        schema.additionalProperties,
        root,
        resolving,
        depth + 1,
      )}>>`;
    }
    fields.push("readonly [key: string]: unknown");
  }
  return fields.length === 0 ? "Record<string, never>" : `{ ${fields.join("; ")} }`;
}

function inferredTypes(schema: Record<string, unknown>): string[] {
  if (isObject(schema.properties) || Object.hasOwn(schema, "additionalProperties")) {
    return ["object"];
  }
  if (Object.hasOwn(schema, "items") || Array.isArray(schema.prefixItems)) return ["array"];
  return [];
}

function resolveLocalReference(root: unknown, reference: string): unknown {
  let current = root;
  for (const encoded of reference.slice(2).split("/")) {
    if (!isObject(current)) return undefined;
    const segment = encoded.replace(/~1/gu, "/").replace(/~0/gu, "~");
    if (!Object.hasOwn(current, segment)) return undefined;
    current = current[segment];
  }
  return current;
}

function literalType(value: unknown): string {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) return `readonly [${value.map(literalType).join(", ")}]`;
  if (isObject(value)) {
    return `{ ${Object.entries(value)
      .sort(([left], [right]) => compareCanonicalStrings(left, right))
      .map(([key, child]) => `readonly ${identifierOrQuoted(key)}: ${literalType(child)}`)
      .join("; ")} }`;
  }
  return "unknown";
}

function union(values: string[]): string {
  const unique = [...new Set(values)];
  if (unique.includes("unknown")) return "unknown";
  if (unique.length === 0) return "never";
  return unique.length === 1 ? unique[0]! : unique.map(parenthesizeComposite).join(" | ");
}

function intersection(values: string[]): string {
  const unique = [...new Set(values.filter((value) => value !== "unknown"))];
  return unique.length === 0
    ? "unknown"
    : unique.length === 1
      ? unique[0]!
      : unique.map(parenthesizeComposite).join(" & ");
}

function parenthesizeComposite(value: string): string {
  return /[|&]/u.test(value) ? `(${value})` : value;
}

function identifierOrQuoted(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value) ? value : JSON.stringify(value);
}

function boundedDoc(value: string | undefined): string | null {
  if (!value) return null;
  const normalized = value.replace(/\s+/gu, " ").trim().replace(/\*\//gu, "*\\/");
  if (!normalized) return null;
  return normalized.length <= 512 ? normalized : `${normalized.slice(0, 509)}...`;
}

function renderDoc(value: string, indent: number): string[] {
  return [`${spaces(indent)}/** ${value} */`];
}

function spaces(count: number): string {
  return " ".repeat(count);
}

function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
