#!/usr/bin/env bun
import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const styles = join(root, "styles");
const sources = ["tokens.css", "components.css", "responsive.css"] as const;
const output = join(styles, "compiled.css");
const banner = "/* Generated by packages/ui/scripts/build-css.ts. Do not edit directly. */\n";
const compiled = `${banner}${(
  await Promise.all(sources.map((file) => readFile(join(styles, file), "utf8")))
)
  .map((content) => content.trimEnd())
  .join("\n\n")}\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== compiled) throw new Error("@opengeni/ui compiled.css is stale");
} else {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== compiled) await writeFile(output, compiled);
}
