import { describe, expect, test } from "bun:test";
import {
  allocateProgrammaticPaths,
  digestCanonicalJson,
  generateCanonicalToolDeclarations,
  normalizeCanonicalToolResult,
} from "@opengeni/tool-runtime";
import {
  createAttemptToolEnvironment,
  digestAttemptToolCatalog,
  generateCodemodeDeclarations,
  type AttemptToolDefinition,
} from "../src";

const scope = {
  accountId: "11111111-1111-4111-8111-111111111111",
  workspaceId: "22222222-2222-4222-8222-222222222222",
  sessionId: "33333333-3333-4333-8333-333333333333",
  turnId: "44444444-4444-4444-8444-444444444444",
  attemptId: "55555555-5555-4555-8555-555555555555",
  executionGeneration: 1,
};

function definition(
  serverId: string,
  toolName: string,
  overrides: Partial<AttemptToolDefinition> = {},
): AttemptToolDefinition {
  return {
    identity: { serverId, toolName },
    modelName: `${serverId}__${toolName}`,
    description: `Run ${toolName}`,
    inputSchema: { type: "object", additionalProperties: false },
    source: "mcp",
    approval: "none",
    execute: async () => ({ content: [] }),
    ...overrides,
  };
}

describe("Code Mode caller-neutral substrate parity", () => {
  test("retains catalog ordering, paths, digest, and declarations byte-for-byte", () => {
    const definitions = [
      definition("foo-bar", "1-search", {
        inputSchema: {
          type: "object",
          properties: { query: { type: "string" } },
          required: ["query"],
          additionalProperties: false,
        },
        outputSchema: {
          type: "object",
          properties: { hits: { type: "array", items: { type: "string" } } },
          required: ["hits"],
          additionalProperties: false,
        },
      }),
      definition("foo_bar", "1_search", { modelName: "foo_bar__1_search" }),
    ];
    const environment = createAttemptToolEnvironment({
      scope,
      generation: 3,
      createdAt: new Date("2026-08-29T12:00:00.000Z"),
      definitions,
    });
    const catalog = environment.catalog;

    expect(catalog.entries.map((entry) => entry.identity)).toEqual(
      definitions.map((entry) => entry.identity),
    );
    expect(catalog.entries.map((entry) => entry.codemodePath)).toEqual(
      allocateProgrammaticPaths(
        definitions.map((entry) => ({
          identity: entry.identity,
          ...(entry.codemodePath ? { programmaticPath: entry.codemodePath } : {}),
        })),
        { resolveSecondaryCollisions: false },
      ),
    );

    const { digest, createdAt: _createdAt, ...authoritative } = catalog;
    expect(digest).toBe(digestCanonicalJson(authoritative));
    const { digest: _digest, ...unsigned } = catalog;
    expect(digestAttemptToolCatalog(unsigned)).toBe(digest);

    const genericDeclaration = generateCanonicalToolDeclarations({
      moduleSpecifier: "@opengeni/codemode",
      interfaceName: "CodemodeGeneratedTools",
      entries: catalog.entries.map((entry) => ({
        programmaticPath: entry.codemodePath,
        ...(entry.title === undefined ? {} : { title: entry.title }),
        ...(entry.description === undefined ? {} : { description: entry.description }),
        inputSchema: entry.inputSchema,
        ...(entry.outputSchema === undefined ? {} : { outputSchema: entry.outputSchema }),
      })),
      callOptionsType: "CodemodeCallOptions",
      defaultResultType: "CodemodeToolResult",
      importTypes: ["CodemodeCallOptions", "CodemodeToolResult"],
      headerLines: [
        "// Generated by @opengeni/codemode. Do not edit.",
        `// Attempt catalog digest: ${catalog.digest}`,
      ],
      argumentName: "argumentsValue",
      pathLabel: "Codemode",
    });
    expect(generateCodemodeDeclarations(catalog)).toBe(genericDeclaration);
  });

  test("retains exact loose MCP result normalization", async () => {
    const environment = createAttemptToolEnvironment({
      scope,
      generation: 1,
      definitions: [
        definition("docs", "search", {
          execute: async () => ({
            content: [{ type: "text", text: "done", providerField: "retained" }],
            structuredContent: { ok: true },
            providerResultField: true,
          }),
        }),
      ],
    });
    const result = await environment.callModel({
      modelName: "docs__search",
      arguments: {},
      subjectId: "agent:test",
    });
    expect(result).toEqual(
      normalizeCanonicalToolResult({
        content: [{ type: "text", text: "done", providerField: "retained" }],
        structuredContent: { ok: true },
        providerResultField: true,
      }),
    );
  });
});
