/** Presentation-only artifact surface. Import from `@opengeni/react/artifacts/presentation`. */
export {
  EditablePresentationArtifactSurface,
  type EditablePresentationArtifactSurfaceProps,
} from "./components/artifacts/editable-presentation";
export {
  PresentationArtifactSurface,
  PresentationEditor,
  PresentationProjectionArtifactSurface,
  PresentationProjectionEditor,
  type PresentationArtifactSurfaceProps,
  type PresentationCommit,
  type PresentationCommitHandler,
  type PresentationEditorProps,
  type PresentationEditorProjection,
  type PresentationProjectionArtifactSurfaceProps,
  type PresentationProjectionChart,
  type PresentationProjectionChartSeries,
  type PresentationProjectionConnector,
  type PresentationProjectionEditorProps,
  type PresentationProjectionElementMetadata,
  type PresentationProjectionElement,
  type PresentationProjectionFill,
  type PresentationProjectionGroup,
  type PresentationProjectionImage,
  type PresentationProjectionLine,
  type PresentationProjectionPosition,
  type PresentationProjectionRichText,
  type PresentationProjectionShape,
  type PresentationProjectionTable,
  type PresentationProjectionTableCell,
  type PresentationProjectionTextParagraph,
  type PresentationProjectionTextRun,
  type PresentationProjectionTextStyle,
  type PresentationSlideProjection,
} from "./components/artifacts/presentation-editor";
