import type { AttemptToolCatalog } from "@opengeni/contracts";
import { generateCanonicalToolDeclarations, jsonSchemaToTypeScript } from "@opengeni/tool-runtime";
import { parseVerifiedAttemptToolCatalog } from "./index";

export type GenerateCodemodeDeclarationsOptions = {
  /** Package whose augmentable CodemodeGeneratedTools interface owns the namespace. */
  moduleSpecifier?: string;
};

/**
 * Generate declaration merging for one exact, digest-pinned attempt catalog.
 * Types improve authoring only; runtime catalog validation remains authoritative.
 */
export function generateCodemodeDeclarations(
  catalog: AttemptToolCatalog,
  options: GenerateCodemodeDeclarationsOptions = {},
): string {
  const verified = parseVerifiedAttemptToolCatalog(catalog);
  const moduleSpecifier = options.moduleSpecifier ?? "@opengeni/codemode";
  return generateCanonicalToolDeclarations({
    moduleSpecifier,
    interfaceName: "CodemodeGeneratedTools",
    entries: verified.entries.map((entry) => ({
      programmaticPath: entry.codemodePath,
      ...(entry.title === undefined ? {} : { title: entry.title }),
      ...(entry.description === undefined ? {} : { description: entry.description }),
      inputSchema: entry.inputSchema,
      ...(entry.outputSchema === undefined ? {} : { outputSchema: entry.outputSchema }),
    })),
    callOptionsType: "CodemodeCallOptions",
    defaultResultType: "CodemodeToolResult",
    importTypes: ["CodemodeCallOptions", "CodemodeToolResult"],
    headerLines: [
      "// Generated by @opengeni/codemode. Do not edit.",
      `// Attempt catalog digest: ${verified.digest}`,
    ],
    argumentName: "argumentsValue",
    pathLabel: "Codemode",
  });
}

/** Compatibility export for existing Code Mode declaration consumers. */
export { jsonSchemaToTypeScript };
