-- Agent-generated session display title.
--
-- A session gets a short title generated by the agent itself (via the
-- set_session_title first-party tool) — not a separate LLM call. `title` is
-- NULL until set, in which case the UI keeps falling back to the
-- initialMessage-derived label. `title_source` records who set it ('agent' for
-- auto/agent writes, 'user' for a manual rename); a user-set title is permanent
-- and the clobber guard (title_source IS DISTINCT FROM 'user') protects it from
-- later agent writes. Both nullable, no backfill.
ALTER TABLE "sessions"
  ADD COLUMN IF NOT EXISTS "title" text,
  ADD COLUMN IF NOT EXISTS "title_source" text;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'opengeni_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO opengeni_app;
  END IF;
END $$;
