/**
 * The organization MCP server's action catalog: every public API route as one
 * callable action, derived from the public surface manifest. Regenerate with
 * `bun scripts/public-api/action-catalog.ts --write`; a test fails when the
 * committed catalog drifts from the manifest.
 */
import surface from "./surface.gen.json";

export type { ActionCatalogEntry } from "../../apps/api/src/mcp/action-catalog-types";
import type { ActionCatalogEntry } from "../../apps/api/src/mcp/action-catalog-types";

/**
 * Routes an agent must never drive, each with the reason. They stay in the
 * browser by design: Opengeni's own sign-in, and approving or managing agent
 * connections (an agent must not approve or widen its own access).
 */
export const ACTION_CATALOG_EXEMPTIONS: ReadonlyArray<{ pattern: RegExp; reason: string }> = [
  { pattern: /^\/v1\/auth\//, reason: "Opengeni sign-in itself" },
  { pattern: /^\/v1\/mcp-connections\//, reason: "approving an agent sign-in" },
  {
    pattern: /^\/v1\/organizations\/:organizationId\/mcp-connections/,
    reason: "managing connected agents",
  },
];

export function isActionCatalogExempt(path: string): boolean {
  return ACTION_CATALOG_EXEMPTIONS.some((exemption) => exemption.pattern.test(path));
}

/** SDK helpers that wrap many routes; they never name one action. */
const GENERIC_SDK_NAMES = new Set([
  "createSessionProxyHandler",
  "connectTransport",
  "forWorkspace",
]);

export function buildActionCatalog(
  routes: ReadonlyArray<{
    method: string;
    path: string;
    sdk: string[];
    request: string[];
    response: string[];
  }> = surface.routes,
): ActionCatalogEntry[] {
  const included = routes.filter((route) => !isActionCatalogExempt(route.path));
  const preferred = included.map((route) => {
    const names = route.sdk.map((name) => name.split(".").pop()!);
    return names.find((name) => !GENERIC_SDK_NAMES.has(name)) ?? names[0]!;
  });
  const counts = new Map<string, number>();
  for (const name of preferred) counts.set(name, (counts.get(name) ?? 0) + 1);
  return included
    .map((route, index) => {
      const name = preferred[index]!;
      return {
        id: counts.get(name) === 1 ? name : `${route.method} ${route.path}`,
        method: route.method,
        path: route.path,
        request: [...route.request],
        response: [...route.response],
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

export function renderActionCatalog(entries: ActionCatalogEntry[]): string {
  return `// Generated by scripts/public-api/action-catalog.ts from surface.gen.json. Do not edit.
import type { ActionCatalogEntry } from "./action-catalog-types";

export const ACTION_CATALOG: readonly ActionCatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;
}

export const ACTION_CATALOG_PATH = new URL(
  "../../apps/api/src/mcp/action-catalog.gen.ts",
  import.meta.url,
);

if (import.meta.main && process.argv.includes("--write")) {
  await Bun.write(ACTION_CATALOG_PATH, renderActionCatalog(buildActionCatalog()));
  console.log(`[action-catalog] wrote ${ACTION_CATALOG_PATH.pathname}`);
}
