#!/usr/bin/env bash
# Full local OpenGeni stack for one checkout / git worktree.
# Isolates Docker Compose project + host ports so parallel worktrees do not share
# Postgres/NATS/Temporal/MinIO or race on :8000/:3000.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ ! -f .env ]; then
  cp .env.example .env
  echo "Created .env from .env.example. Configure model and sandbox credentials before running agent sessions."
fi

set -a
# shellcheck disable=SC1091
. ./.env
set +a

# Local managed credentials (Codex subscriptions, MCP credentials, etc.) still
# need encryption at rest. Generate one worktree-local key on first boot and
# persist it in the ignored .env so restarts can decrypt previously stored rows.
if [ -z "${OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY:-}" ]; then
  OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(32).toString("base64"))')"
  export OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY
  {
    printf '\n%s\n' '# Generated by scripts/dev-stack.sh for local development. Do not commit.'
    printf 'OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY=%s\n' "$OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY"
  } >>.env
  echo "Generated and persisted a local environments encryption key in .env."
fi

# The local UI exposes Codex connection management, so its model-catalog and
# runtime gates must agree by default. An explicit false still disables it.
if [ -z "${OPENGENI_CODEX_SUBSCRIPTION_ENABLED:-}" ]; then
  OPENGENI_CODEX_SUBSCRIPTION_ENABLED=true
  export OPENGENI_CODEX_SUBSCRIPTION_ENABLED
  {
    printf '\n%s\n' '# Added by scripts/dev-stack.sh for local Codex/realtime development.'
    printf 'OPENGENI_CODEX_SUBSCRIPTION_ENABLED=true\n'
  } >>.env
  echo "Enabled and persisted Codex subscription support in .env."
else
  export OPENGENI_CODEX_SUBSCRIPTION_ENABLED
fi

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
}

# Compose project identity: directory basename (unique per linked worktree path).
# Ignore ambient COMPOSE_PROJECT_NAME from the parent shell — a prior export of
# `opengeni` would otherwise collapse every worktree onto one project. Override
# only via OPENGENI_COMPOSE_PROJECT in .env / the environment.
if [ -n "${OPENGENI_COMPOSE_PROJECT:-}" ]; then
  COMPOSE_PROJECT_NAME="$(slugify "$OPENGENI_COMPOSE_PROJECT")"
else
  COMPOSE_PROJECT_NAME="$(slugify "$(basename "$(pwd)")")"
  # Bare main-checkout directory name only — never rewrite an explicit override
  # (operators may still want COMPOSE project `opengeni` for legacy volumes).
  if [ "$COMPOSE_PROJECT_NAME" = "opengeni" ]; then
    COMPOSE_PROJECT_NAME="opengeni-main"
  fi
fi
export COMPOSE_PROJECT_NAME

# A stopped host dev process intentionally leaves this worktree's dependency
# containers running. Reuse the generated ports when those exact compose
# services still exist; otherwise a restart mistakes its own containers for a
# collision and needlessly moves Postgres/Temporal/MinIO to new ports.
reuse_runtime_ports=0
if [ -f .env.runtime ] &&
  [ "$(sed -n 's/^COMPOSE_PROJECT_NAME=//p' .env.runtime | tail -1)" = "$COMPOSE_PROJECT_NAME" ] &&
  [ -n "$(docker compose ps -q 2>/dev/null)" ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env.runtime
  set +a
  reuse_runtime_ports=1
fi

port_available() {
  if command -v lsof >/dev/null 2>&1; then
    ! lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
    return
  fi
  if command -v ss >/dev/null 2>&1; then
    ! ss -H -ltn "sport = :$1" | grep -q .
    return
  fi
  if command -v netstat >/dev/null 2>&1; then
    ! netstat -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "(^|[:.])$1$"
    return
  fi
  ! (echo >"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

# Ports already claimed by this run (avoids MinIO data/console sharing one bind).
DECLARED_PORTS=()

port_claimed() {
  local candidate="$1"
  local claimed
  for claimed in "${DECLARED_PORTS[@]+"${DECLARED_PORTS[@]}"}"; do
    [ "$claimed" = "$candidate" ] && return 0
  done
  return 1
}

claim_port() {
  DECLARED_PORTS+=("$1")
}

# Prefer the default port when free. Otherwise scan nearby ports.
# Host-port values from a copied .env are ignored unless OPENGENI_PIN_PORTS=1,
# so parallel worktrees do not sticky-collide on another checkout's ports.
choose_port() {
  local var_name="$1"
  local default_port="$2"
  local pinned="${!var_name:-}"

  if [ "$reuse_runtime_ports" = "1" ] && [ -n "$pinned" ]; then
    export "$var_name=$pinned"
    claim_port "$pinned"
    return
  fi

  if [ "${OPENGENI_PIN_PORTS:-0}" = "1" ] && [ -n "$pinned" ]; then
    if ! port_claimed "$pinned" && port_available "$pinned"; then
      export "$var_name=$pinned"
      claim_port "$pinned"
      return
    fi
    echo "Pinned ${var_name}=${pinned} is busy; selecting a free port instead." >&2
  fi

  if ! port_claimed "$default_port" && port_available "$default_port"; then
    export "$var_name=$default_port"
    claim_port "$default_port"
    return
  fi
  # Prefer default+1000… when defaults are taken. Window is wide so many
  # parallel worktrees can each grab distinct host ports; still capped so we
  # do not walk the whole ephemeral range on failure.
  local port
  local scan_start=$((default_port + 1000))
  local scan_end=$((default_port + 2999))
  if [ "$scan_end" -gt 65535 ]; then
    scan_end=65535
  fi
  for port in $(seq "$scan_start" "$scan_end"); do
    if ! port_claimed "$port" && port_available "$port"; then
      export "$var_name=$port"
      claim_port "$port"
      echo "Port ${default_port} is in use; using ${var_name}=${port} for this worktree stack."
      return
    fi
  done
  echo "Could not find a free host port for ${var_name} in ${scan_start}-${scan_end}." >&2
  exit 1
}

# Rewrite the port on loopback URLs/hosts so a copied .env cannot point this
# worktree at another stack's infra. Non-loopback URLs are left alone.
# Handles postgres://user@host:port/db, nats://host:port, http(s)://host:port,
# and bare host:port (Temporal).
rewrite_loopback_port() {
  local value="$1"
  local new_port="$2"
  if [[ "$value" =~ @127\.0\.0\.1:[0-9]+ ]] || [[ "$value" =~ @localhost:[0-9]+ ]]; then
    printf '%s' "$value" | sed -E "s/@(127\.0\.0\.1|localhost):[0-9]+/@\1:${new_port}/"
    return
  fi
  # Any URI scheme on loopback (nats://, http://, https://, …).
  if [[ "$value" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*://127\.0\.0\.1:[0-9]+ ]] ||
    [[ "$value" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*://localhost:[0-9]+ ]]; then
    printf '%s' "$value" | sed -E "s#^([a-zA-Z][a-zA-Z0-9+.-]*://)(127\.0\.0\.1|localhost):[0-9]+#\1\2:${new_port}#"
    return
  fi
  if [[ "$value" =~ ^127\.0\.0\.1:[0-9]+$ ]] || [[ "$value" =~ ^localhost:[0-9]+$ ]]; then
    printf '%s' "$value" | sed -E "s/^(127\.0\.0\.1|localhost):[0-9]+/\1:${new_port}/"
    return
  fi
  printf '%s' "$value"
}

choose_port OPENGENI_POSTGRES_HOST_PORT 5432
choose_port OPENGENI_NATS_HOST_PORT 4222
choose_port OPENGENI_NATS_MONITOR_HOST_PORT 8222
choose_port OPENGENI_TEMPORAL_HOST_PORT 7233
choose_port OPENGENI_MINIO_HOST_PORT 9000
choose_port OPENGENI_MINIO_CONSOLE_HOST_PORT 9001
choose_port OPENGENI_API_PORT 8000
choose_port OPENGENI_WORKER_HTTP_PORT 8001
choose_port OPENGENI_TURN_WORKER_HTTP_PORT 8002
choose_port OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT 9465
choose_port OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT 9466
choose_port OPENGENI_WEB_PORT 3000

default_database_url="postgres://opengeni_app:opengeni_app@127.0.0.1:5432/opengeni"
if [ -z "${OPENGENI_DATABASE_URL:-}" ] || [ "${OPENGENI_DATABASE_URL}" = "$default_database_url" ]; then
  export OPENGENI_DATABASE_URL="postgres://opengeni_app:opengeni_app@127.0.0.1:${OPENGENI_POSTGRES_HOST_PORT}/opengeni"
else
  export OPENGENI_DATABASE_URL="$(rewrite_loopback_port "$OPENGENI_DATABASE_URL" "$OPENGENI_POSTGRES_HOST_PORT")"
fi

default_migrations_database_url="postgres://opengeni:opengeni@127.0.0.1:5432/opengeni"
if [ -z "${OPENGENI_MIGRATIONS_DATABASE_URL:-}" ] || [ "${OPENGENI_MIGRATIONS_DATABASE_URL}" = "$default_migrations_database_url" ]; then
  export OPENGENI_MIGRATIONS_DATABASE_URL="postgres://opengeni:opengeni@127.0.0.1:${OPENGENI_POSTGRES_HOST_PORT}/opengeni"
else
  export OPENGENI_MIGRATIONS_DATABASE_URL="$(rewrite_loopback_port "$OPENGENI_MIGRATIONS_DATABASE_URL" "$OPENGENI_POSTGRES_HOST_PORT")"
fi

# Artifact services use separate, least-privileged login roles. Generate real
# per-launch credentials, converge the roles through provision-roles below, and
# persist only the resulting DSNs in the ignored .env.runtime for this stack.
OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER=opengeni_artifact_materializer
OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER=opengeni_artifact_outbox_dispatcher
OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(24).toString("base64url"))')"
OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(24).toString("base64url"))')"
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD

database_url_for_role() {
  local role="$1"
  local password="$2"
  OPENGENI_ROLE_DSN_BASE="$OPENGENI_MIGRATIONS_DATABASE_URL" \
    OPENGENI_ROLE_DSN_USER="$role" \
    OPENGENI_ROLE_DSN_PASSWORD="$password" \
    bun -e '
      const url = new URL(Bun.env.OPENGENI_ROLE_DSN_BASE);
      if (!['"'"'postgres:'"'"', '"'"'postgresql:'"'"'].includes(url.protocol)) throw new Error('"'"'Local database URL must use PostgreSQL'"'"');
      if (!['"'"'localhost'"'"', '"'"'127.0.0.1'"'"', '"'"'[::1]'"'"'].includes(url.hostname.toLowerCase())) throw new Error('"'"'Local artifact services require a loopback database URL'"'"');
      url.username = Bun.env.OPENGENI_ROLE_DSN_USER;
      url.password = Bun.env.OPENGENI_ROLE_DSN_PASSWORD;
      process.stdout.write(url.href);
    '
}

OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL="$(database_url_for_role \
  "$OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER" \
  "$OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD")"
OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL="$(database_url_for_role \
  "$OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER" \
  "$OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD")"
OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE="$OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER"
OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE="$OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER"
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE

default_nats_url="nats://127.0.0.1:4222"
if [ -z "${OPENGENI_NATS_URL:-}" ] || [ "${OPENGENI_NATS_URL}" = "$default_nats_url" ]; then
  export OPENGENI_NATS_URL="nats://127.0.0.1:${OPENGENI_NATS_HOST_PORT}"
else
  export OPENGENI_NATS_URL="$(rewrite_loopback_port "$OPENGENI_NATS_URL" "$OPENGENI_NATS_HOST_PORT")"
fi

default_temporal_host="127.0.0.1:7233"
if [ -z "${OPENGENI_TEMPORAL_HOST:-}" ] || [ "${OPENGENI_TEMPORAL_HOST}" = "$default_temporal_host" ]; then
  export OPENGENI_TEMPORAL_HOST="127.0.0.1:${OPENGENI_TEMPORAL_HOST_PORT}"
else
  export OPENGENI_TEMPORAL_HOST="$(rewrite_loopback_port "$OPENGENI_TEMPORAL_HOST" "$OPENGENI_TEMPORAL_HOST_PORT")"
fi

default_object_endpoint="http://127.0.0.1:9000"
if [ -z "${OPENGENI_OBJECT_STORAGE_ENDPOINT:-}" ] || [ "${OPENGENI_OBJECT_STORAGE_ENDPOINT}" = "$default_object_endpoint" ]; then
  export OPENGENI_OBJECT_STORAGE_ENDPOINT="http://127.0.0.1:${OPENGENI_MINIO_HOST_PORT}"
else
  export OPENGENI_OBJECT_STORAGE_ENDPOINT="$(rewrite_loopback_port "$OPENGENI_OBJECT_STORAGE_ENDPOINT" "$OPENGENI_MINIO_HOST_PORT")"
fi

# API/workers run on the host in local development, so their authenticated
# object-storage client must use the host endpoint. `minio:9000` is reachable
# only from compose/sandbox containers and previously made every server-side
# upload fail after the expensive provider work had already completed.
default_internal_object_endpoint="http://minio:9000"
if [ -z "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT:-}" ] ||
  [ "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT}" = "$default_internal_object_endpoint" ] ||
  [ "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT}" = "$default_object_endpoint" ]; then
  export OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT="${OPENGENI_OBJECT_STORAGE_ENDPOINT}"
else
  export OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT="$(rewrite_loopback_port "$OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT" "$OPENGENI_MINIO_HOST_PORT")"
fi

default_sandbox_object_endpoint="http://host.docker.internal:9000"
if [ -z "${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT:-}" ] || [ "${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT}" = "$default_sandbox_object_endpoint" ]; then
  # In-compose DNS; host port mapping is irrelevant inside the docker network.
  export OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT="http://minio:9000"
fi

# Sandbox containers must join *this* worktree's compose network.
export OPENGENI_DOCKER_NETWORK="${COMPOSE_PROJECT_NAME}_default"

default_vite_api_base_url="http://127.0.0.1:8000"
if [ -z "${VITE_API_BASE_URL:-}" ] || [ "${VITE_API_BASE_URL}" = "$default_vite_api_base_url" ]; then
  export VITE_API_BASE_URL="http://127.0.0.1:${OPENGENI_API_PORT}"
else
  export VITE_API_BASE_URL="$(rewrite_loopback_port "$VITE_API_BASE_URL" "$OPENGENI_API_PORT")"
fi

# A clean checkout must establish the canonical workspace package links before
# the generated facade is verified. The facade never searches alternate roots.
bun install --frozen-lockfile

# Local editable-artifact authority uses a separately typed current-host bundle.
# It is rebuilt only when its exact source/toolchain fingerprint or smoke receipt
# changes. Production's complete eight-target locator remains untouched and a
# development manifest is rejected by the runtime when NODE_ENV=production.
unset OPENGENI_ARTIFACT_RUNTIME_MANIFEST
export NODE_ENV=development
artifact_development_root="$(pwd)/.opengeni/artifact-runtime-development"
bun scripts/prepare-development-artifact-runtime.ts \
  --repository-root "$(pwd)" \
  --output "$artifact_development_root"
export OPENGENI_ARTIFACT_DEVELOPMENT_RUNTIME_MANIFEST="${artifact_development_root}/installation.development.json"
export OPENGENI_ARTIFACT_TOOL_ENTRY="${artifact_development_root}/skill-facade-entry.mjs"
export OPENGENI_ARTIFACT_MATERIALIZER_EXECUTABLE="${artifact_development_root}/opengeni-artifact-materializer"
export OPENGENI_ARTIFACT_MATERIALIZER_ENABLED=true
export OPENGENI_ARTIFACT_OUTBOX_ENABLED=true
export OPENGENI_ARTIFACT_LOCAL_DEVELOPMENT=true
export OPENGENI_ARTIFACT_MATERIALIZER_UNSANDBOXED_DEVELOPMENT=true
export OPENGENI_ARTIFACT_MATERIALIZER_HTTP_HOST=127.0.0.1

# Sibling shells / `bun run dev:*` source this after `.env`. Use printf so URL
# passwords containing `$` / backticks cannot break the file via heredoc expansion.
{
  printf '%s\n' "# Generated by scripts/dev-stack.sh for worktree stack ${COMPOSE_PROJECT_NAME}. Do not commit."
  printf 'COMPOSE_PROJECT_NAME=%s\n' "${COMPOSE_PROJECT_NAME}"
  printf 'OPENGENI_DOCKER_NETWORK=%s\n' "${OPENGENI_DOCKER_NETWORK}"
  printf 'OPENGENI_POSTGRES_HOST_PORT=%s\n' "${OPENGENI_POSTGRES_HOST_PORT}"
  printf 'OPENGENI_NATS_HOST_PORT=%s\n' "${OPENGENI_NATS_HOST_PORT}"
  printf 'OPENGENI_NATS_MONITOR_HOST_PORT=%s\n' "${OPENGENI_NATS_MONITOR_HOST_PORT}"
  printf 'OPENGENI_TEMPORAL_HOST_PORT=%s\n' "${OPENGENI_TEMPORAL_HOST_PORT}"
  printf 'OPENGENI_MINIO_HOST_PORT=%s\n' "${OPENGENI_MINIO_HOST_PORT}"
  printf 'OPENGENI_MINIO_CONSOLE_HOST_PORT=%s\n' "${OPENGENI_MINIO_CONSOLE_HOST_PORT}"
  printf 'OPENGENI_API_PORT=%s\n' "${OPENGENI_API_PORT}"
  printf 'OPENGENI_WORKER_HTTP_PORT=%s\n' "${OPENGENI_WORKER_HTTP_PORT}"
  printf 'OPENGENI_TURN_WORKER_HTTP_PORT=%s\n' "${OPENGENI_TURN_WORKER_HTTP_PORT}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT}"
  printf 'OPENGENI_WEB_PORT=%s\n' "${OPENGENI_WEB_PORT}"
  printf 'OPENGENI_DATABASE_URL=%s\n' "${OPENGENI_DATABASE_URL}"
  printf 'OPENGENI_MIGRATIONS_DATABASE_URL=%s\n' "${OPENGENI_MIGRATIONS_DATABASE_URL}"
  printf 'OPENGENI_NATS_URL=%s\n' "${OPENGENI_NATS_URL}"
  printf 'OPENGENI_TEMPORAL_HOST=%s\n' "${OPENGENI_TEMPORAL_HOST}"
  printf 'OPENGENI_OBJECT_STORAGE_ENDPOINT=%s\n' "${OPENGENI_OBJECT_STORAGE_ENDPOINT}"
  printf 'OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT=%s\n' "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT}"
  printf 'OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT=%s\n' "${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT}"
  printf 'OPENGENI_CODEX_SUBSCRIPTION_ENABLED=%s\n' "${OPENGENI_CODEX_SUBSCRIPTION_ENABLED}"
  printf 'NODE_ENV=%s\n' "${NODE_ENV}"
  printf 'OPENGENI_ARTIFACT_DEVELOPMENT_RUNTIME_MANIFEST=%s\n' "${OPENGENI_ARTIFACT_DEVELOPMENT_RUNTIME_MANIFEST}"
  printf 'OPENGENI_ARTIFACT_TOOL_ENTRY=%s\n' "${OPENGENI_ARTIFACT_TOOL_ENTRY}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_EXECUTABLE=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_EXECUTABLE}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_ENABLED=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_ENABLED}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_ENABLED=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_ENABLED}"
  printf 'OPENGENI_ARTIFACT_LOCAL_DEVELOPMENT=%s\n' "${OPENGENI_ARTIFACT_LOCAL_DEVELOPMENT}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_UNSANDBOXED_DEVELOPMENT=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_UNSANDBOXED_DEVELOPMENT}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_HTTP_HOST=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_HTTP_HOST}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE}"
  printf 'VITE_API_BASE_URL=%s\n' "${VITE_API_BASE_URL}"
} >.env.runtime

echo "OpenGeni worktree stack: compose project=${COMPOSE_PROJECT_NAME}"
echo "  api=${VITE_API_BASE_URL}  web=http://127.0.0.1:${OPENGENI_WEB_PORT}"
echo "  postgres=127.0.0.1:${OPENGENI_POSTGRES_HOST_PORT}  nats=${OPENGENI_NATS_URL}"
echo "  temporal=${OPENGENI_TEMPORAL_HOST}  minio=${OPENGENI_OBJECT_STORAGE_ENDPOINT}"
echo "  artifact-materializer=http://127.0.0.1:${OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT}  artifact-outbox=http://127.0.0.1:${OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT}"
echo "  Wrote .env.runtime (source it in sibling shells)."

docker compose up -d postgres nats temporal minio minio-init
(cd packages/db && bun run migrate)
(cd packages/db && bun run provision-roles)
# The sidecars need only their dedicated DSNs. Do not leak raw provisioning
# passwords into API/web/worker child environments after role convergence.
unset OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD
unset OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD
if [ "${OPENGENI_CATALOG_IMPORT_ENABLED:-true}" = "true" ]; then
  OPENGENI_DATABASE_URL="$OPENGENI_MIGRATIONS_DATABASE_URL" \
    bun scripts/import-integrations-catalog.ts \
      --snapshot data/catalog/integrations-snapshot.json --if-changed --skip-logos
fi
if [ "${OPENGENI_SANDBOX_BACKEND:-docker}" != "none" ]; then
  docker build -f docker/sandbox.Dockerfile -t opengeni-sandbox:local .
else
  echo "Skipping sandbox image build (OPENGENI_SANDBOX_BACKEND=none)."
fi

pids=()
cleanup() {
  if [ "${#pids[@]}" -gt 0 ]; then
    kill "${pids[@]}" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT INT TERM

(cd apps/api && bun run dev) &
pids+=("$!")

(cd apps/worker && OPENGENI_WORKER_ROLE=control bun run dev:watch) &
pids+=("$!")

(cd apps/worker && OPENGENI_WORKER_ROLE=turn \
  OPENGENI_WORKER_HTTP_PORT="${OPENGENI_TURN_WORKER_HTTP_PORT}" bun run dev:watch) &
pids+=("$!")

(cd apps/worker && bun run start:artifact-materializer) &
pids+=("$!")

(cd apps/worker && bun run start:artifact-outbox) &
pids+=("$!")

(cd apps/web && bun x vite dev --port "${OPENGENI_WEB_PORT}" --host 0.0.0.0) &
pids+=("$!")

wait
exit_code=$?
cleanup
exit "$exit_code"
