#!/usr/bin/env bash
# Full local OpenGeni stack for one checkout / git worktree.
# Isolates Docker Compose project + host ports so parallel worktrees do not share
# Postgres/NATS/Temporal/MinIO or race on :8000/:3000.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ ! -f .env ]; then
  cp .env.example .env
  echo "Created .env from .env.example. Configure model and sandbox credentials before running agent sessions."
fi

set -a
# shellcheck disable=SC1091
. ./.env
set +a

# Connected Machines are part of the normal localhost product surface. Keep the
# deployment/config-library default fail-closed, but make `bun run dev`
# self-contained even for an older copied .env that predates this setting. An
# explicit false remains authoritative for local testing of the disabled state.
if [ -z "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-}" ]; then
  OPENGENI_SANDBOX_SELFHOSTED_ENABLED=true
fi
export OPENGENI_SANDBOX_SELFHOSTED_ENABLED

# Browser and Computer are first-class localhost surfaces. Production remains
# fail-closed in packages/config, while a development stack should exercise the
# same interactive capabilities users are actively building. Preserve explicit
# false values so disabled-policy states are still easy to test intentionally.
if [ -z "${OPENGENI_SANDBOX_DESKTOP_ENABLED:-}" ]; then
  OPENGENI_SANDBOX_DESKTOP_ENABLED=true
fi
if [ -z "${OPENGENI_SANDBOX_DESKTOP_INTERACTIVE:-}" ]; then
  OPENGENI_SANDBOX_DESKTOP_INTERACTIVE=true
fi
if [ -z "${OPENGENI_COMPUTER_USE_ENABLED:-}" ]; then
  OPENGENI_COMPUTER_USE_ENABLED=true
fi
export OPENGENI_SANDBOX_DESKTOP_ENABLED
export OPENGENI_SANDBOX_DESKTOP_INTERACTIVE
export OPENGENI_COMPUTER_USE_ENABLED

# The Modal SDK natively supports MODAL_TOKEN_* and ~/.modal.toml, while the
# deployment-facing OpenGeni config intentionally requires explicit credentials.
# Bridge those standard local sources for this dev process only; never persist
# the imported token in .env or .env.runtime.
if [ "${OPENGENI_SANDBOX_BACKEND:-docker}" = "modal" ] &&
  [ -z "${OPENGENI_MODAL_TOKEN_ID:-}" ] &&
  [ -z "${OPENGENI_MODAL_TOKEN_SECRET:-}" ]; then
  if [ -n "${MODAL_TOKEN_ID:-}" ] && [ -n "${MODAL_TOKEN_SECRET:-}" ]; then
    OPENGENI_MODAL_TOKEN_ID="$MODAL_TOKEN_ID"
    OPENGENI_MODAL_TOKEN_SECRET="$MODAL_TOKEN_SECRET"
  elif [ -f "${HOME}/.modal.toml" ]; then
    IFS=$'\t' read -r OPENGENI_MODAL_TOKEN_ID OPENGENI_MODAL_TOKEN_SECRET < <(
      bun -e '
        const config = Bun.TOML.parse(await Bun.file(`${Bun.env.HOME}/.modal.toml`).text());
        const requested = Bun.env.MODAL_PROFILE?.trim();
        const entries = Object.entries(config).filter(([, value]) =>
          value !== null && typeof value === "object"
        );
        const selected = requested
          ? entries.find(([name]) => name === requested)
          : entries.find(([, value]) => value.active === true);
        if (!selected) throw new Error("No active Modal profile is configured");
        const profile = selected[1];
        if (typeof profile.token_id !== "string" || typeof profile.token_secret !== "string") {
          throw new Error(`Modal profile ${selected[0]} has no token pair`);
        }
        process.stdout.write(`${profile.token_id}\t${profile.token_secret}\n`);
      '
    )
  fi
  export OPENGENI_MODAL_TOKEN_ID OPENGENI_MODAL_TOKEN_SECRET
fi

# Local managed credentials (Codex subscriptions, MCP credentials, etc.) still
# need encryption at rest. Generate one worktree-local key on first boot and
# persist it in the ignored .env so restarts can decrypt previously stored rows.
if [ -z "${OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY:-}" ]; then
  OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(32).toString("base64"))')"
  export OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY
  {
    printf '\n%s\n' '# Generated by scripts/dev-stack.sh for local development. Do not commit.'
    printf 'OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY=%s\n' "$OPENGENI_ENVIRONMENTS_ENCRYPTION_KEY"
  } >>.env
  echo "Generated and persisted a local environments encryption key in .env."
fi

# Connected-machine enrollment and streaming are ordinary local-development
# capabilities. A clean checkout must not require the operator to invent and
# repeatedly export signing secrets before the Machines dialog can work. Keep
# these worktree-local values stable across restarts so already-enrolled agents
# remain valid; production/configured deployments continue to provide their own.
if [ "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-false}" = "true" ]; then
  if [ -z "${OPENGENI_ENROLLMENT_SIGNING_SECRET:-}" ] &&
    [ -z "${OPENGENI_DELEGATION_SECRET:-}" ]; then
    OPENGENI_ENROLLMENT_SIGNING_SECRET="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(32).toString("base64url"))')"
    export OPENGENI_ENROLLMENT_SIGNING_SECRET
    {
      printf '\n%s\n' '# Generated by scripts/dev-stack.sh for local Connected Machines.'
      printf 'OPENGENI_ENROLLMENT_SIGNING_SECRET=%s\n' "$OPENGENI_ENROLLMENT_SIGNING_SECRET"
    } >>.env
    echo "Generated and persisted a local Connected Machine enrollment secret in .env."
  fi
  if [ -z "${OPENGENI_SELFHOSTED_RELAY_TOKEN_SECRET:-}" ] &&
    [ -z "${OPENGENI_STREAM_TOKEN_SECRET:-}" ] &&
    [ -z "${OPENGENI_DELEGATION_SECRET:-}" ]; then
    OPENGENI_STREAM_TOKEN_SECRET="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(32).toString("base64url"))')"
    export OPENGENI_STREAM_TOKEN_SECRET
    {
      printf '%s\n' '# Generated by scripts/dev-stack.sh for local Connected Machine streams.'
      printf 'OPENGENI_STREAM_TOKEN_SECRET=%s\n' "$OPENGENI_STREAM_TOKEN_SECRET"
    } >>.env
    echo "Generated and persisted a local Connected Machine stream secret in .env."
  fi
  if [ -z "${OPENGENI_AGENT_STABLE_VERSION:-}" ]; then
    OPENGENI_AGENT_STABLE_VERSION="$(bun -e '
      const manifest = Bun.TOML.parse(await Bun.file("agent/Cargo.toml").text());
      process.stdout.write(manifest.workspace.package.version);
    ')"
    export OPENGENI_AGENT_STABLE_VERSION
  fi
fi

# The local UI exposes Codex connection management, so its model-catalog and
# runtime gates must agree by default. An explicit false still disables it.
if [ -z "${OPENGENI_CODEX_SUBSCRIPTION_ENABLED:-}" ]; then
  OPENGENI_CODEX_SUBSCRIPTION_ENABLED=true
  export OPENGENI_CODEX_SUBSCRIPTION_ENABLED
  {
    printf '\n%s\n' '# Added by scripts/dev-stack.sh for local Codex/realtime development.'
    printf 'OPENGENI_CODEX_SUBSCRIPTION_ENABLED=true\n'
  } >>.env
  echo "Enabled and persisted Codex subscription support in .env."
else
  export OPENGENI_CODEX_SUBSCRIPTION_ENABLED
fi

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
}

# Compose project identity: directory basename (unique per linked worktree path).
# Ignore ambient COMPOSE_PROJECT_NAME from the parent shell — a prior export of
# `opengeni` would otherwise collapse every worktree onto one project. Override
# only via OPENGENI_COMPOSE_PROJECT in .env / the environment.
if [ -n "${OPENGENI_COMPOSE_PROJECT:-}" ]; then
  COMPOSE_PROJECT_NAME="$(slugify "$OPENGENI_COMPOSE_PROJECT")"
else
  COMPOSE_PROJECT_NAME="$(slugify "$(basename "$(pwd)")")"
  # Bare main-checkout directory name only — never rewrite an explicit override
  # (operators may still want COMPOSE project `opengeni` for legacy volumes).
  if [ "$COMPOSE_PROJECT_NAME" = "opengeni" ]; then
    COMPOSE_PROJECT_NAME="opengeni-main"
  fi
fi
export COMPOSE_PROJECT_NAME

# A stopped host dev process intentionally leaves this worktree's dependency
# containers running. Reuse the generated ports when those exact compose
# services still exist; otherwise a restart mistakes its own containers for a
# collision and needlessly moves Postgres/Temporal/MinIO to new ports.
reuse_runtime_ports=0
if [ -f .env.runtime ] &&
  [ "$(sed -n 's/^COMPOSE_PROJECT_NAME=//p' .env.runtime | tail -1)" = "$COMPOSE_PROJECT_NAME" ] &&
  [ -n "$(docker compose ps -q 2>/dev/null)" ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env.runtime
  set +a
  reuse_runtime_ports=1
fi

port_available() {
  if command -v lsof >/dev/null 2>&1; then
    ! lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
    return
  fi
  if command -v ss >/dev/null 2>&1; then
    ! ss -H -ltn "sport = :$1" | grep -q .
    return
  fi
  if command -v netstat >/dev/null 2>&1; then
    ! netstat -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "(^|[:.])$1$"
    return
  fi
  ! (echo >"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

# Ports already claimed by this run (avoids MinIO data/console sharing one bind).
DECLARED_PORTS=()

port_claimed() {
  local candidate="$1"
  local claimed
  for claimed in "${DECLARED_PORTS[@]+"${DECLARED_PORTS[@]}"}"; do
    [ "$claimed" = "$candidate" ] && return 0
  done
  return 1
}

claim_port() {
  DECLARED_PORTS+=("$1")
}

# Prefer the default port when free. Otherwise scan nearby ports.
# Host-port values from a copied .env are ignored unless OPENGENI_PIN_PORTS=1,
# so parallel worktrees do not sticky-collide on another checkout's ports.
choose_port() {
  local var_name="$1"
  local default_port="$2"
  local pinned="${!var_name:-}"

  if [ "$reuse_runtime_ports" = "1" ] && [ -n "$pinned" ]; then
    export "$var_name=$pinned"
    claim_port "$pinned"
    return
  fi

  if [ "${OPENGENI_PIN_PORTS:-0}" = "1" ] && [ -n "$pinned" ]; then
    if ! port_claimed "$pinned" && port_available "$pinned"; then
      export "$var_name=$pinned"
      claim_port "$pinned"
      return
    fi
    echo "Pinned ${var_name}=${pinned} is busy; selecting a free port instead." >&2
  fi

  if ! port_claimed "$default_port" && port_available "$default_port"; then
    export "$var_name=$default_port"
    claim_port "$default_port"
    return
  fi
  # Prefer default+1000… when defaults are taken. Window is wide so many
  # parallel worktrees can each grab distinct host ports; still capped so we
  # do not walk the whole ephemeral range on failure.
  local port
  local scan_start=$((default_port + 1000))
  local scan_end=$((default_port + 2999))
  if [ "$scan_end" -gt 65535 ]; then
    scan_end=65535
  fi
  for port in $(seq "$scan_start" "$scan_end"); do
    if ! port_claimed "$port" && port_available "$port"; then
      export "$var_name=$port"
      claim_port "$port"
      echo "Port ${default_port} is in use; using ${var_name}=${port} for this worktree stack."
      return
    fi
  done
  echo "Could not find a free host port for ${var_name} in ${scan_start}-${scan_end}." >&2
  exit 1
}

# Rewrite the port on loopback URLs/hosts so a copied .env cannot point this
# worktree at another stack's infra. Non-loopback URLs are left alone.
# Handles postgres://user@host:port/db, nats://host:port, http(s)://host:port,
# and bare host:port (Temporal).
rewrite_loopback_port() {
  local value="$1"
  local new_port="$2"
  if [[ "$value" =~ @127\.0\.0\.1:[0-9]+ ]] || [[ "$value" =~ @localhost:[0-9]+ ]]; then
    printf '%s' "$value" | sed -E "s/@(127\.0\.0\.1|localhost):[0-9]+/@\1:${new_port}/"
    return
  fi
  # Any URI scheme on loopback (nats://, http://, https://, …).
  if [[ "$value" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*://127\.0\.0\.1:[0-9]+ ]] ||
    [[ "$value" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*://localhost:[0-9]+ ]]; then
    printf '%s' "$value" | sed -E "s#^([a-zA-Z][a-zA-Z0-9+.-]*://)(127\.0\.0\.1|localhost):[0-9]+#\1\2:${new_port}#"
    return
  fi
  if [[ "$value" =~ ^127\.0\.0\.1:[0-9]+$ ]] || [[ "$value" =~ ^localhost:[0-9]+$ ]]; then
    printf '%s' "$value" | sed -E "s/^(127\.0\.0\.1|localhost):[0-9]+/\1:${new_port}/"
    return
  fi
  printf '%s' "$value"
}

choose_port OPENGENI_POSTGRES_HOST_PORT 5432
choose_port OPENGENI_NATS_HOST_PORT 4222
choose_port OPENGENI_NATS_MONITOR_HOST_PORT 8222
choose_port OPENGENI_TEMPORAL_HOST_PORT 7233
choose_port OPENGENI_MINIO_HOST_PORT 9000
choose_port OPENGENI_MINIO_CONSOLE_HOST_PORT 9001
choose_port OPENGENI_API_PORT 8000
choose_port OPENGENI_WORKER_HTTP_PORT 8001
choose_port OPENGENI_TURN_WORKER_HTTP_PORT 8002
choose_port OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT 9465
choose_port OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT 9466
choose_port OPENGENI_WEB_PORT 3000
if [ "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-false}" = "true" ]; then
  choose_port OPENGENI_RELAY_HOST_PORT 8280
fi

pids=()
owned_ngrok_tunnel_name=""
cleanup() {
  if [ -n "$owned_ngrok_tunnel_name" ]; then
    curl -fsS -X DELETE "http://127.0.0.1:4040/api/tunnels/${owned_ngrok_tunnel_name}" \
      >/dev/null 2>&1 || true
  fi
  if [ "${#pids[@]}" -gt 0 ]; then
    kill "${pids[@]}" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT INT TERM

default_database_url="postgres://opengeni_app:opengeni_app@127.0.0.1:5432/opengeni"
if [ -z "${OPENGENI_DATABASE_URL:-}" ] || [ "${OPENGENI_DATABASE_URL}" = "$default_database_url" ]; then
  export OPENGENI_DATABASE_URL="postgres://opengeni_app:opengeni_app@127.0.0.1:${OPENGENI_POSTGRES_HOST_PORT}/opengeni"
else
  export OPENGENI_DATABASE_URL="$(rewrite_loopback_port "$OPENGENI_DATABASE_URL" "$OPENGENI_POSTGRES_HOST_PORT")"
fi

# Forced-RLS role provisioning needs the plaintext password for the application
# role. Local development already carries that credential in its loopback DSN,
# so derive it when a sparse worktree .env omits the redundant standalone var.
if [ -z "${OPENGENI_APP_DATABASE_PASSWORD:-}" ]; then
  OPENGENI_APP_DATABASE_PASSWORD="$(
    OPENGENI_LOCAL_DATABASE_URL="$OPENGENI_DATABASE_URL" bun -e '
      const url = new URL(Bun.env.OPENGENI_LOCAL_DATABASE_URL);
      if (!["localhost", "127.0.0.1", "[::1]"].includes(url.hostname.toLowerCase())) {
        throw new Error("Automatic local app-role password derivation requires a loopback database URL");
      }
      if (!url.password) throw new Error("Local application database URL must contain a password");
      process.stdout.write(decodeURIComponent(url.password));
    '
  )"
fi
export OPENGENI_APP_DATABASE_PASSWORD

default_migrations_database_url="postgres://opengeni:opengeni@127.0.0.1:5432/opengeni"
if [ -z "${OPENGENI_MIGRATIONS_DATABASE_URL:-}" ] || [ "${OPENGENI_MIGRATIONS_DATABASE_URL}" = "$default_migrations_database_url" ]; then
  export OPENGENI_MIGRATIONS_DATABASE_URL="postgres://opengeni:opengeni@127.0.0.1:${OPENGENI_POSTGRES_HOST_PORT}/opengeni"
else
  export OPENGENI_MIGRATIONS_DATABASE_URL="$(rewrite_loopback_port "$OPENGENI_MIGRATIONS_DATABASE_URL" "$OPENGENI_POSTGRES_HOST_PORT")"
fi

# Artifact services use separate, least-privileged login roles. Generate real
# per-launch credentials, converge the roles through provision-roles below, and
# persist only the resulting DSNs in the ignored .env.runtime for this stack.
OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER=opengeni_artifact_materializer
OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER=opengeni_artifact_outbox_dispatcher
OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(24).toString("base64url"))')"
OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(24).toString("base64url"))')"
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD

database_url_for_role() {
  local role="$1"
  local password="$2"
  OPENGENI_ROLE_DSN_BASE="$OPENGENI_MIGRATIONS_DATABASE_URL" \
    OPENGENI_ROLE_DSN_USER="$role" \
    OPENGENI_ROLE_DSN_PASSWORD="$password" \
    bun -e '
      const url = new URL(Bun.env.OPENGENI_ROLE_DSN_BASE);
      if (!['"'"'postgres:'"'"', '"'"'postgresql:'"'"'].includes(url.protocol)) throw new Error('"'"'Local database URL must use PostgreSQL'"'"');
      if (!['"'"'localhost'"'"', '"'"'127.0.0.1'"'"', '"'"'[::1]'"'"'].includes(url.hostname.toLowerCase())) throw new Error('"'"'Local artifact services require a loopback database URL'"'"');
      url.username = Bun.env.OPENGENI_ROLE_DSN_USER;
      url.password = Bun.env.OPENGENI_ROLE_DSN_PASSWORD;
      process.stdout.write(url.href);
    '
}

OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL="$(database_url_for_role \
  "$OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER" \
  "$OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD")"
OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL="$(database_url_for_role \
  "$OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER" \
  "$OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD")"
OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE="$OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_USER"
OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE="$OPENGENI_ARTIFACT_OUTBOX_DATABASE_USER"
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL
export OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE
export OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE

default_nats_url="nats://127.0.0.1:4222"
if [ -z "${OPENGENI_NATS_URL:-}" ] || [ "${OPENGENI_NATS_URL}" = "$default_nats_url" ]; then
  export OPENGENI_NATS_URL="nats://127.0.0.1:${OPENGENI_NATS_HOST_PORT}"
else
  export OPENGENI_NATS_URL="$(rewrite_loopback_port "$OPENGENI_NATS_URL" "$OPENGENI_NATS_HOST_PORT")"
fi

# A localhost Machines command must contain endpoints reachable by an agent on
# this host, and the served installer must fetch through this API rather than the
# public CDN. Explicit non-loopback operator values still win unchanged.
if [ "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-false}" = "true" ]; then
  default_selfhosted_nats_url="nats://127.0.0.1:4222"
  if [ -z "${OPENGENI_SELFHOSTED_NATS_URL:-}" ] ||
    [ "${OPENGENI_SELFHOSTED_NATS_URL}" = "$default_selfhosted_nats_url" ]; then
    export OPENGENI_SELFHOSTED_NATS_URL="$OPENGENI_NATS_URL"
  else
    export OPENGENI_SELFHOSTED_NATS_URL="$(rewrite_loopback_port "$OPENGENI_SELFHOSTED_NATS_URL" "$OPENGENI_NATS_HOST_PORT")"
  fi

  default_selfhosted_relay_url="ws://127.0.0.1:8280"
  if [ -z "${OPENGENI_SELFHOSTED_RELAY_URL:-}" ] ||
    [ "${OPENGENI_SELFHOSTED_RELAY_URL}" = "$default_selfhosted_relay_url" ]; then
    export OPENGENI_SELFHOSTED_RELAY_URL="ws://127.0.0.1:${OPENGENI_RELAY_HOST_PORT}"
  else
    export OPENGENI_SELFHOSTED_RELAY_URL="$(rewrite_loopback_port "$OPENGENI_SELFHOSTED_RELAY_URL" "$OPENGENI_RELAY_HOST_PORT")"
  fi

  if [ -z "${OPENGENI_PUBLIC_BASE_URL:-}" ]; then
    export OPENGENI_PUBLIC_BASE_URL="http://127.0.0.1:${OPENGENI_API_PORT}"
  fi
fi

default_temporal_host="127.0.0.1:7233"
if [ -z "${OPENGENI_TEMPORAL_HOST:-}" ] || [ "${OPENGENI_TEMPORAL_HOST}" = "$default_temporal_host" ]; then
  export OPENGENI_TEMPORAL_HOST="127.0.0.1:${OPENGENI_TEMPORAL_HOST_PORT}"
else
  export OPENGENI_TEMPORAL_HOST="$(rewrite_loopback_port "$OPENGENI_TEMPORAL_HOST" "$OPENGENI_TEMPORAL_HOST_PORT")"
fi

default_object_endpoint="http://127.0.0.1:9000"
if [ -z "${OPENGENI_OBJECT_STORAGE_ENDPOINT:-}" ] || [ "${OPENGENI_OBJECT_STORAGE_ENDPOINT}" = "$default_object_endpoint" ]; then
  export OPENGENI_OBJECT_STORAGE_ENDPOINT="http://127.0.0.1:${OPENGENI_MINIO_HOST_PORT}"
else
  export OPENGENI_OBJECT_STORAGE_ENDPOINT="$(rewrite_loopback_port "$OPENGENI_OBJECT_STORAGE_ENDPOINT" "$OPENGENI_MINIO_HOST_PORT")"
fi

# docker-compose.yml owns this worktree's local MinIO and fixes its development
# credential pair. Sparse acceptance .env files should not have to repeat it.
if [ -z "${OPENGENI_OBJECT_STORAGE_ACCESS_KEY_ID:-}" ] &&
  [ -z "${OPENGENI_OBJECT_STORAGE_SECRET_ACCESS_KEY:-}" ]; then
  export OPENGENI_OBJECT_STORAGE_ACCESS_KEY_ID=minioadmin
  export OPENGENI_OBJECT_STORAGE_SECRET_ACCESS_KEY=minioadmin
fi

# API/workers run on the host in local development, so their authenticated
# object-storage client must use the host endpoint. `minio:9000` is reachable
# only from compose/sandbox containers and previously made every server-side
# upload fail after the expensive provider work had already completed.
default_internal_object_endpoint="http://minio:9000"
if [ -z "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT:-}" ] ||
  [ "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT}" = "$default_internal_object_endpoint" ] ||
  [ "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT}" = "$default_object_endpoint" ]; then
  export OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT="${OPENGENI_OBJECT_STORAGE_ENDPOINT}"
else
  export OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT="$(rewrite_loopback_port "$OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT" "$OPENGENI_MINIO_HOST_PORT")"
fi

default_sandbox_object_endpoint="http://host.docker.internal:9000"
if [ -z "${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT:-}" ] || [ "${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT}" = "$default_sandbox_object_endpoint" ]; then
  # In-compose DNS; host port mapping is irrelevant inside the docker network.
  export OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT="http://minio:9000"
fi

# A managed Modal sandbox cannot resolve compose-only `minio` DNS or reach the
# host loopback endpoint embedded in local presigned URLs. Give remote sandboxes
# a short-lived HTTPS route to this worktree's private MinIO. The object store
# remains credential-protected and every write still requires its object-scoped
# signed URL. Operators can bypass this local convenience by configuring any
# already-sandbox-reachable endpoint.
if [ "${OPENGENI_SANDBOX_BACKEND:-docker}" = "modal" ]; then
  sandbox_object_host="$({
    OPENGENI_LOCAL_OBJECT_ENDPOINT="$OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT" bun -e '
      const url = new URL(Bun.env.OPENGENI_LOCAL_OBJECT_ENDPOINT);
      process.stdout.write(url.hostname.toLowerCase());
    '
  })"
  if [ "$sandbox_object_host" = "minio" ] ||
    [ "$sandbox_object_host" = "host.docker.internal" ] ||
    [ "$sandbox_object_host" = "127.0.0.1" ] ||
    [ "$sandbox_object_host" = "localhost" ] ||
    [[ "$sandbox_object_host" = *.ngrok-free.app ]] ||
    [[ "$sandbox_object_host" = *.ngrok-free.dev ]] ||
    [[ "$sandbox_object_host" = *.ngrok.io ]]; then
    if ! command -v ngrok >/dev/null 2>&1; then
      echo "Modal local development needs ngrok or an externally reachable OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT." >&2
      exit 1
    fi

    ngrok_tunnel_url() {
      local tunnels
      tunnels="$(curl -fsS http://127.0.0.1:4040/api/tunnels 2>/dev/null || true)"
      if [ -z "$tunnels" ]; then
        return 0
      fi
      OPENGENI_NGROK_TUNNELS="$tunnels" OPENGENI_NGROK_TARGET_PORT="$OPENGENI_MINIO_HOST_PORT" bun -e '
        const value = JSON.parse(Bun.env.OPENGENI_NGROK_TUNNELS);
        const port = Bun.env.OPENGENI_NGROK_TARGET_PORT;
        const tunnel = value.tunnels?.find((candidate) => {
          try {
            const target = new URL(candidate.config?.addr);
            return (target.port || (target.protocol === "https:" ? "443" : "80")) === port;
          } catch {
            return false;
          }
        });
        if (typeof tunnel?.public_url === "string" && tunnel.public_url.startsWith("https://")) {
          process.stdout.write(tunnel.public_url);
        }
      '
    }

    sandbox_object_tunnel_url="$(ngrok_tunnel_url)"
    if [ -z "$sandbox_object_tunnel_url" ]; then
      if curl -fsS http://127.0.0.1:4040/api/tunnels >/dev/null 2>&1; then
        owned_ngrok_tunnel_name="opengeni-${COMPOSE_PROJECT_NAME}-minio"
        ngrok_request="$({
          OPENGENI_NGROK_NAME="$owned_ngrok_tunnel_name" OPENGENI_NGROK_TARGET_PORT="$OPENGENI_MINIO_HOST_PORT" bun -e '
            process.stdout.write(JSON.stringify({
              name: Bun.env.OPENGENI_NGROK_NAME,
              proto: "http",
              addr: `http://127.0.0.1:${Bun.env.OPENGENI_NGROK_TARGET_PORT}`,
            }));
          '
        })"
        curl -fsS -X POST -H "content-type: application/json" --data "$ngrok_request" \
          http://127.0.0.1:4040/api/tunnels >/dev/null
      else
        mkdir -p .opengeni
        ngrok http "http://127.0.0.1:${OPENGENI_MINIO_HOST_PORT}" \
          --log ".opengeni/ngrok-object-storage.log" --log-format json &
        pids+=("$!")
      fi
      for _attempt in $(seq 1 100); do
        sandbox_object_tunnel_url="$(ngrok_tunnel_url)"
        [ -n "$sandbox_object_tunnel_url" ] && break
        sleep 0.1
      done
    fi
    if [ -z "$sandbox_object_tunnel_url" ]; then
      echo "Could not establish the Modal-to-MinIO development tunnel." >&2
      exit 1
    fi
    export OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT="$sandbox_object_tunnel_url"
    echo "  modal-object-storage=${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT}"
  fi
fi

# Sandbox containers must join *this* worktree's compose network.
export OPENGENI_DOCKER_NETWORK="${COMPOSE_PROJECT_NAME}_default"

default_vite_api_base_url="http://127.0.0.1:8000"
if [ -z "${VITE_API_BASE_URL:-}" ] || [ "${VITE_API_BASE_URL}" = "$default_vite_api_base_url" ]; then
  export VITE_API_BASE_URL="http://127.0.0.1:${OPENGENI_API_PORT}"
else
  export VITE_API_BASE_URL="$(rewrite_loopback_port "$VITE_API_BASE_URL" "$OPENGENI_API_PORT")"
fi

# Connected-machine terminal/desktop/browser streams need the separate relay
# data plane. Production runs it as its own workload; local development must do
# the same whenever the configured relay URL points back at this machine. Until
# now dev-stack started the control plane but silently omitted the relay, so an
# enrolled machine looked online while every live surface failed at :8280.
start_local_relay=0
if [ "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-false}" = "true" ] &&
  [ -n "${OPENGENI_SELFHOSTED_RELAY_URL:-}" ]; then
  IFS=$'\t' read -r relay_hostname relay_port < <(
    OPENGENI_LOCAL_RELAY_URL="$OPENGENI_SELFHOSTED_RELAY_URL" bun -e '
      const url = new URL(Bun.env.OPENGENI_LOCAL_RELAY_URL);
      const port = url.port || (url.protocol === "wss:" ? "443" : "80");
      process.stdout.write(`${url.hostname}\t${port}\n`);
    '
  )
  if [ "$relay_hostname" = "127.0.0.1" ] || [ "$relay_hostname" = "localhost" ]; then
    OPENGENI_RELAY_BIND="127.0.0.1:${relay_port}"
    OPENGENI_RELAY_TOKEN_SECRET="${OPENGENI_SELFHOSTED_RELAY_TOKEN_SECRET:-${OPENGENI_STREAM_TOKEN_SECRET:-${OPENGENI_DELEGATION_SECRET:-}}}"
    if [ -z "$OPENGENI_RELAY_TOKEN_SECRET" ]; then
      echo "Connected-machine local relay requires OPENGENI_SELFHOSTED_RELAY_TOKEN_SECRET or OPENGENI_STREAM_TOKEN_SECRET." >&2
      exit 1
    fi
    export OPENGENI_RELAY_BIND OPENGENI_RELAY_TOKEN_SECRET
    start_local_relay=1
  fi
fi

# A clean checkout must establish the canonical workspace package links before
# the generated facade is verified. The facade never searches alternate roots.
bun install --frozen-lockfile

# Connected Machines use the real NATS auth-callout boundary in local development,
# too. Generate one stable worktree-local signing identity/password pair, render an
# ignored NATS configuration, and authenticate the API/worker control connections.
# Reusing these values across restarts keeps existing enrollments valid; parallel
# worktrees remain isolated by their own .env, Compose project, ports, and config.
if [ "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-false}" = "true" ]; then
  generated_nats_env=0
  if [ -z "${OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED:-}" ]; then
    IFS=$'\t' read -r OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED \
      OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY < <(
      bun -e '
        import { nkeys } from "@opengeni/events";
        const account = nkeys.createAccount();
        const seed = new TextDecoder().decode(account.getSeed());
        process.stdout.write(`${seed}\t${account.getPublicKey()}\n`);
      '
    )
    generated_nats_env=1
  else
    derived_nats_public_key="$({
      OPENGENI_LOCAL_NATS_SEED="$OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED" bun -e '
        import { nkeys } from "@opengeni/events";
        const key = nkeys.fromSeed(new TextEncoder().encode(Bun.env.OPENGENI_LOCAL_NATS_SEED));
        process.stdout.write(key.getPublicKey());
      '
    })"
    if [ -n "${OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY:-}" ] &&
      [ "$OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY" != "$derived_nats_public_key" ]; then
      echo "OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY does not match its account seed." >&2
      exit 1
    fi
    OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY="$derived_nats_public_key"
  fi
  OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_NAME="${OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_NAME:-APP}"
  OPENGENI_SELFHOSTED_NATS_CALLOUT_USER="${OPENGENI_SELFHOSTED_NATS_CALLOUT_USER:-auth}"
  OPENGENI_SELFHOSTED_NATS_CONTROL_USER="${OPENGENI_SELFHOSTED_NATS_CONTROL_USER:-control}"
  if [ -z "${OPENGENI_SELFHOSTED_NATS_CALLOUT_PASSWORD:-}" ]; then
    OPENGENI_SELFHOSTED_NATS_CALLOUT_PASSWORD="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(24).toString("base64url"))')"
    generated_nats_env=1
  fi
  if [ -z "${OPENGENI_SELFHOSTED_NATS_CONTROL_PASSWORD:-}" ]; then
    OPENGENI_SELFHOSTED_NATS_CONTROL_PASSWORD="$(bun -e 'import { randomBytes } from "node:crypto"; process.stdout.write(randomBytes(24).toString("base64url"))')"
    generated_nats_env=1
  fi
  export OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED
  export OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY
  export OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_NAME
  export OPENGENI_SELFHOSTED_NATS_CALLOUT_USER
  export OPENGENI_SELFHOSTED_NATS_CALLOUT_PASSWORD
  export OPENGENI_SELFHOSTED_NATS_CONTROL_USER
  export OPENGENI_SELFHOSTED_NATS_CONTROL_PASSWORD
  if [ "$generated_nats_env" = "1" ]; then
    {
      printf '\n%s\n' '# Generated by scripts/dev-stack.sh for local NATS auth-callout.'
      printf 'OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED=%s\n' "$OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED"
      printf 'OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY=%s\n' "$OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY"
      printf 'OPENGENI_SELFHOSTED_NATS_CALLOUT_PASSWORD=%s\n' "$OPENGENI_SELFHOSTED_NATS_CALLOUT_PASSWORD"
      printf 'OPENGENI_SELFHOSTED_NATS_CONTROL_PASSWORD=%s\n' "$OPENGENI_SELFHOSTED_NATS_CONTROL_PASSWORD"
    } >>.env
    echo "Generated and persisted the local NATS auth-callout identity in .env."
  fi
  OPENGENI_NATS_CONFIG_FILE="$(pwd)/.opengeni/nats-auth-callout.conf"
  export OPENGENI_NATS_CONFIG_FILE
  bun scripts/prepare-development-nats-config.ts --output "$OPENGENI_NATS_CONFIG_FILE" >/dev/null
fi

# Local editable-artifact authority uses a separately typed current-host bundle.
# It is rebuilt only when its exact source/toolchain fingerprint or smoke receipt
# changes. Production's complete eight-target locator remains untouched and a
# development manifest is rejected by the runtime when NODE_ENV=production.
unset OPENGENI_ARTIFACT_RUNTIME_MANIFEST
export NODE_ENV=development
artifact_development_root="$(pwd)/.opengeni/artifact-runtime-development"
bun scripts/prepare-development-artifact-runtime.ts \
  --repository-root "$(pwd)" \
  --output "$artifact_development_root"
export OPENGENI_ARTIFACT_DEVELOPMENT_RUNTIME_MANIFEST="${artifact_development_root}/installation.development.json"
export OPENGENI_ARTIFACT_TOOL_ENTRY="${artifact_development_root}/skill-facade-entry.mjs"
export OPENGENI_ARTIFACT_MATERIALIZER_EXECUTABLE="${artifact_development_root}/opengeni-artifact-materializer"
export OPENGENI_ARTIFACT_MATERIALIZER_ENABLED=true
export OPENGENI_ARTIFACT_OUTBOX_ENABLED=true
export OPENGENI_ARTIFACT_LOCAL_DEVELOPMENT=true
export OPENGENI_ARTIFACT_MATERIALIZER_UNSANDBOXED_DEVELOPMENT=true
export OPENGENI_ARTIFACT_MATERIALIZER_HTTP_HOST=127.0.0.1

# Native agent skills require a source-matched Linux runtime inside the sandbox
# image. Resolve only the exact clean-HEAD CI artifact; never reuse a stale
# bundle. Ordinary API/web development remains available when no exact artifact
# exists, while OPENGENI_REQUIRE_SANDBOX_ARTIFACT_RUNTIME=1 makes that mismatch
# an explicit startup failure for artifact-engine work.
sandbox_runtime_bundle=".opengeni/no-artifact-runtime-for-this-source"
sandbox_source_tag="$(git rev-parse --short=12 HEAD)"
if [ "${OPENGENI_SANDBOX_BACKEND:-docker}" = "docker" ]; then
  if sandbox_runtime_json="$(bun scripts/resolve-development-sandbox-runtime.ts \
    --repository-root "$(pwd)" \
    --output "$(pwd)/.release/artifact-runtime")"; then
    sandbox_source_tag="$(printf '%s' "$sandbox_runtime_json" | bun -e 'const value=await Bun.stdin.json();process.stdout.write(value.sourceTag)')"
    sandbox_runtime_bundle=".release/artifact-runtime"
    OPENGENI_SANDBOX_ARTIFACT_RUNTIME_ENABLED=true
    echo "Using exact-head sandbox artifact runtime (${sandbox_source_tag})."
  else
    OPENGENI_SANDBOX_ARTIFACT_RUNTIME_ENABLED=false
    if [ "${OPENGENI_REQUIRE_SANDBOX_ARTIFACT_RUNTIME:-0}" = "1" ]; then
      echo "Exact-head sandbox artifact runtime is required but unavailable." >&2
      exit 1
    fi
    echo "Exact-head sandbox artifact runtime unavailable; standalone local Office file operations are disabled." >&2
  fi
  OPENGENI_DOCKER_IMAGE="opengeni-sandbox:local-${sandbox_source_tag}"
  export OPENGENI_DOCKER_IMAGE OPENGENI_SANDBOX_ARTIFACT_RUNTIME_ENABLED
fi

# Sibling shells / `bun run dev:*` source this after `.env`. Use printf so URL
# passwords containing `$` / backticks cannot break the file via heredoc expansion.
{
  printf '%s\n' "# Generated by scripts/dev-stack.sh for worktree stack ${COMPOSE_PROJECT_NAME}. Do not commit."
  printf 'COMPOSE_PROJECT_NAME=%s\n' "${COMPOSE_PROJECT_NAME}"
  printf 'OPENGENI_DOCKER_NETWORK=%s\n' "${OPENGENI_DOCKER_NETWORK}"
  printf 'OPENGENI_DOCKER_IMAGE=%s\n' "${OPENGENI_DOCKER_IMAGE:-opengeni-sandbox:local}"
  printf 'OPENGENI_SANDBOX_ARTIFACT_RUNTIME_ENABLED=%s\n' "${OPENGENI_SANDBOX_ARTIFACT_RUNTIME_ENABLED:-false}"
  printf 'OPENGENI_POSTGRES_HOST_PORT=%s\n' "${OPENGENI_POSTGRES_HOST_PORT}"
  printf 'OPENGENI_NATS_HOST_PORT=%s\n' "${OPENGENI_NATS_HOST_PORT}"
  printf 'OPENGENI_NATS_MONITOR_HOST_PORT=%s\n' "${OPENGENI_NATS_MONITOR_HOST_PORT}"
  printf 'OPENGENI_NATS_CONFIG_FILE=%s\n' "${OPENGENI_NATS_CONFIG_FILE:-$(pwd)/deploy/nats/local-development.conf}"
  printf 'OPENGENI_TEMPORAL_HOST_PORT=%s\n' "${OPENGENI_TEMPORAL_HOST_PORT}"
  printf 'OPENGENI_MINIO_HOST_PORT=%s\n' "${OPENGENI_MINIO_HOST_PORT}"
  printf 'OPENGENI_MINIO_CONSOLE_HOST_PORT=%s\n' "${OPENGENI_MINIO_CONSOLE_HOST_PORT}"
  printf 'OPENGENI_API_PORT=%s\n' "${OPENGENI_API_PORT}"
  printf 'OPENGENI_WORKER_HTTP_PORT=%s\n' "${OPENGENI_WORKER_HTTP_PORT}"
  printf 'OPENGENI_TURN_WORKER_HTTP_PORT=%s\n' "${OPENGENI_TURN_WORKER_HTTP_PORT}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT}"
  printf 'OPENGENI_WEB_PORT=%s\n' "${OPENGENI_WEB_PORT}"
  if [ "${OPENGENI_SANDBOX_SELFHOSTED_ENABLED:-false}" = "true" ]; then
    printf 'OPENGENI_RELAY_HOST_PORT=%s\n' "${OPENGENI_RELAY_HOST_PORT}"
    printf 'OPENGENI_SELFHOSTED_NATS_URL=%s\n' "${OPENGENI_SELFHOSTED_NATS_URL}"
    printf 'OPENGENI_SELFHOSTED_RELAY_URL=%s\n' "${OPENGENI_SELFHOSTED_RELAY_URL}"
    printf 'OPENGENI_PUBLIC_BASE_URL=%s\n' "${OPENGENI_PUBLIC_BASE_URL}"
    printf 'OPENGENI_AGENT_STABLE_VERSION=%s\n' "${OPENGENI_AGENT_STABLE_VERSION}"
  fi
  if [ "$start_local_relay" = "1" ]; then
    printf 'OPENGENI_RELAY_BIND=%s\n' "${OPENGENI_RELAY_BIND}"
  fi
  printf 'OPENGENI_DATABASE_URL=%s\n' "${OPENGENI_DATABASE_URL}"
  printf 'OPENGENI_MIGRATIONS_DATABASE_URL=%s\n' "${OPENGENI_MIGRATIONS_DATABASE_URL}"
  printf 'OPENGENI_NATS_URL=%s\n' "${OPENGENI_NATS_URL}"
  printf 'OPENGENI_TEMPORAL_HOST=%s\n' "${OPENGENI_TEMPORAL_HOST}"
  printf 'OPENGENI_OBJECT_STORAGE_ENDPOINT=%s\n' "${OPENGENI_OBJECT_STORAGE_ENDPOINT}"
  printf 'OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT=%s\n' "${OPENGENI_OBJECT_STORAGE_INTERNAL_ENDPOINT}"
  printf 'OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT=%s\n' "${OPENGENI_OBJECT_STORAGE_SANDBOX_ENDPOINT}"
  printf 'OPENGENI_CODEX_SUBSCRIPTION_ENABLED=%s\n' "${OPENGENI_CODEX_SUBSCRIPTION_ENABLED}"
  printf 'NODE_ENV=%s\n' "${NODE_ENV}"
  printf 'OPENGENI_ARTIFACT_DEVELOPMENT_RUNTIME_MANIFEST=%s\n' "${OPENGENI_ARTIFACT_DEVELOPMENT_RUNTIME_MANIFEST}"
  printf 'OPENGENI_ARTIFACT_TOOL_ENTRY=%s\n' "${OPENGENI_ARTIFACT_TOOL_ENTRY}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_EXECUTABLE=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_EXECUTABLE}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_ENABLED=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_ENABLED}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_ENABLED=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_ENABLED}"
  printf 'OPENGENI_ARTIFACT_LOCAL_DEVELOPMENT=%s\n' "${OPENGENI_ARTIFACT_LOCAL_DEVELOPMENT}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_UNSANDBOXED_DEVELOPMENT=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_UNSANDBOXED_DEVELOPMENT}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_HTTP_HOST=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_HTTP_HOST}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_URL}"
  printf 'OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE=%s\n' "${OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_ROLE}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_DATABASE_URL}"
  printf 'OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE=%s\n' "${OPENGENI_ARTIFACT_OUTBOX_DATABASE_ROLE}"
  printf 'VITE_API_BASE_URL=%s\n' "${VITE_API_BASE_URL}"
} >.env.runtime

echo "OpenGeni worktree stack: compose project=${COMPOSE_PROJECT_NAME}"
echo "  api=${VITE_API_BASE_URL}  web=http://127.0.0.1:${OPENGENI_WEB_PORT}"
echo "  postgres=127.0.0.1:${OPENGENI_POSTGRES_HOST_PORT}  nats=${OPENGENI_NATS_URL}"
echo "  temporal=${OPENGENI_TEMPORAL_HOST}  minio=${OPENGENI_OBJECT_STORAGE_ENDPOINT}"
echo "  artifact-materializer=http://127.0.0.1:${OPENGENI_ARTIFACT_MATERIALIZER_HTTP_PORT}  artifact-outbox=http://127.0.0.1:${OPENGENI_ARTIFACT_OUTBOX_HTTP_PORT}"
echo "  Wrote .env.runtime (source it in sibling shells)."

docker compose up -d postgres nats temporal minio minio-init
(cd packages/db && bun run migrate)
(cd packages/db && bun run provision-roles)
# The sidecars need only their dedicated DSNs. Do not leak raw provisioning
# passwords into API/web/worker child environments after role convergence.
unset OPENGENI_ARTIFACT_MATERIALIZER_DATABASE_PASSWORD
unset OPENGENI_ARTIFACT_OUTBOX_DATABASE_PASSWORD
if [ "${OPENGENI_CATALOG_IMPORT_ENABLED:-true}" = "true" ]; then
  OPENGENI_DATABASE_URL="$OPENGENI_MIGRATIONS_DATABASE_URL" \
    bun scripts/import-integrations-catalog.ts \
      --snapshot data/catalog/integrations-snapshot.json --if-changed --skip-logos
fi
if [ "${OPENGENI_SANDBOX_BACKEND:-docker}" = "docker" ]; then
  docker build \
    -f docker/sandbox.Dockerfile \
    --build-arg "OPENGENI_ARTIFACT_RUNTIME_BUNDLE=${sandbox_runtime_bundle}" \
    --build-arg "OPENGENI_SOURCE_SHA=$(git rev-parse HEAD)" \
    -t "${OPENGENI_DOCKER_IMAGE}" \
    .
else
  echo "Skipping local Docker sandbox image build (backend=${OPENGENI_SANDBOX_BACKEND:-docker})."
fi

if [ "$start_local_relay" = "1" ]; then
  bash scripts/run-development-relay.sh &
  pids+=("$!")
fi

(cd apps/api && bun run dev) &
pids+=("$!")

(cd apps/worker && OPENGENI_WORKER_ROLE=control bun run dev:watch) &
pids+=("$!")

(cd apps/worker && OPENGENI_WORKER_ROLE=turn \
  OPENGENI_WORKER_HTTP_PORT="${OPENGENI_TURN_WORKER_HTTP_PORT}" bun run dev:watch) &
pids+=("$!")

(cd apps/worker && bun run start:artifact-materializer) &
pids+=("$!")

(cd apps/worker && bun run start:artifact-outbox) &
pids+=("$!")

(cd apps/web && bun x vite dev --port "${OPENGENI_WEB_PORT}" --host 0.0.0.0) &
pids+=("$!")

wait
exit_code=$?
cleanup
exit "$exit_code"
