import { resolve } from "node:path";
const directory = resolve(import.meta.dir, "../packages/react/src/components/artifacts");
const css = await Bun.file(resolve(directory, "visualization-assets/base.css")).text();
const helpers = await Bun.file(resolve(directory, "visualization-assets/helpers.html")).text();
const source =
  "// Generated by scripts/generate-visualization-assets.ts.\nexport const VISUALIZATION_CSS = " +
  JSON.stringify(css) +
  ";\nexport const VISUALIZATION_HELPERS = " +
  JSON.stringify(helpers.replace("<!--__INLINE_VISUALIZATION_FRAGMENT__-->", "")) +
  ";\n";
const output = Bun.file(resolve(directory, "visualization-assets.gen.ts"));
if (process.argv.includes("--check")) {
  if ((await output.text()) !== source) throw new Error("Regenerate visualization assets");
} else if (!(await output.exists()) || (await output.text()) !== source) {
  await Bun.write(output, source);
}
// Preview/export copies are generated from the same source as the chat renderer.
const skillAssets = resolve(
  import.meta.dir,
  "../packages/runtime/src/bundled_default_skills/opengeni-visualize/assets",
);
for (const [name, content] of [
  ["base.css", css],
  ["helpers.html", helpers],
] as const) {
  const file = Bun.file(resolve(skillAssets, name));
  if (process.argv.includes("--check")) {
    if ((await file.text()) !== content) throw new Error("Regenerate visualization skill assets");
  } else if (!(await file.exists()) || (await file.text()) !== content) {
    await Bun.write(file, content);
  }
}
