import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const unicodePath = resolve(
  repoRoot,
  "packages/react/node_modules/@fontsource-variable/noto-sans-jp/unicode.json",
);
const outputPath = resolve(repoRoot, "packages/react/src/lib/noto-sans-jp-loader.generated.ts");
const unicode = JSON.parse(await readFile(unicodePath, "utf8")) as Record<string, string>;
const indexes = Object.keys(unicode)
  .map((key) => /^\[(\d+)]$/.exec(key)?.[1])
  .filter((value): value is string => value !== undefined)
  .map(Number)
  .sort((left, right) => left - right);

if (indexes.length === 0 || indexes.some((value, index) => value !== index)) {
  throw new Error("Noto Sans JP unicode shards are no longer contiguous from zero");
}

const imports = indexes
  .map(
    (index) =>
      `import font${index} from "@fontsource-variable/noto-sans-jp/files/noto-sans-jp-${index}-wght-normal.woff2";`,
  )
  .join("\n");
const urls = indexes.map((index) => `  "[${index}]": font${index},`).join("\n");
const source = `/* This file is generated by scripts/generate-noto-jp-loader.ts. */
import unicodeRanges from "@fontsource-variable/noto-sans-jp/unicode.json";
${imports}

const fontUrls: Record<string, string> = {
${urls}
};
const loads = new Map<string, Promise<void>>();

export async function loadNotoSansJp(text: string): Promise<void> {
  const required = new Set<string>();
  for (const character of text) {
    const codePoint = character.codePointAt(0);
    if (codePoint === undefined) continue;
    for (const [key, range] of Object.entries(unicodeRanges)) {
      if (!fontUrls[key]) continue;
      if (rangeContains(range, codePoint)) {
        required.add(key);
        break;
      }
    }
  }
  await Promise.all([...required].map(loadShard));
}

function loadShard(key: string): Promise<void> {
  const existing = loads.get(key);
  if (existing) return existing;
  const url = fontUrls[key];
  const unicodeRange = (unicodeRanges as Record<string, string>)[key];
  if (!url || !unicodeRange) throw new Error(\`Missing Noto Sans JP shard \${key}\`);
  const loading = new FontFace(
    "Noto Sans JP Variable",
    \`url("\${url}") format("woff2-variations")\`,
    { style: "normal", weight: "100 900", unicodeRange },
  )
    .load()
    .then((font) => {
      document.fonts.add(font);
    })
    .catch((error: unknown) => {
      loads.delete(key);
      throw error;
    });
  loads.set(key, loading);
  return loading;
}

function rangeContains(range: string, codePoint: number): boolean {
  for (const token of range.split(",")) {
    const [startText, endText = startText] = token.trim().slice(2).split("-");
    const start = Number.parseInt(startText ?? "", 16);
    const end = Number.parseInt(endText ?? "", 16);
    if (Number.isFinite(start) && codePoint >= start && codePoint <= end) return true;
  }
  return false;
}
`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== source) {
    throw new Error(
      "generated Noto Sans JP loader is stale; run bun scripts/generate-noto-jp-loader.ts",
    );
  }
  console.log(`verified ${outputPath} with ${indexes.length} unicode shards`);
} else {
  await writeFile(outputPath, source);
  console.log(`generated ${outputPath} with ${indexes.length} unicode shards`);
}
