// Generate the native icon geometry from the exact lucide-react icons the web
// timeline renders, so native rows draw the same glyphs without an icon font.
// Usage: bun scripts/generate-native-icons.ts
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const require = createRequire(join(import.meta.dir, "../packages/react/package.json"));
const lucide = require("lucide-react") as Record<
  string,
  {
    render?: (
      props: object,
      ref: null,
    ) => { props: { iconNode: Array<[string, Record<string, string | number>]> } };
  }
>;

// kebab-case native name → lucide-react export.
const ICONS: Record<string, string> = {
  "arrow-down": "ArrowDownIcon",
  "arrow-up": "ArrowUpIcon",
  bot: "BotIcon",
  box: "BoxIcon",
  brain: "BrainIcon",
  "brain-circuit": "BrainCircuitIcon",
  "calendar-clock": "CalendarClockIcon",
  check: "CheckIcon",
  "chevron-down": "ChevronDownIcon",
  "chevron-left": "ChevronLeftIcon",
  "chevron-right": "ChevronRightIcon",
  "chevron-up": "ChevronUpIcon",
  "circle-alert": "CircleAlertIcon",
  "clock-3": "Clock3Icon",
  "circle-slash": "CircleSlashIcon",
  copy: "CopyIcon",
  "corner-down-right": "CornerDownRightIcon",
  "file-diff": "FileDiffIcon",
  "file-search": "FileSearchIcon",
  "file-text": "FileTextIcon",
  image: "ImageIcon",
  folder: "FolderIcon",
  "folder-git": "FolderGitIcon",
  globe: "GlobeIcon",
  keyboard: "KeyboardIcon",
  "loader-circle": "LoaderCircleIcon",
  "list-ordered": "ListOrderedIcon",
  "key-round": "KeyRoundIcon",
  menu: "MenuIcon",
  "message-circle-question": "MessageCircleQuestionIcon",
  "message-square": "MessageSquareIcon",
  "message-square-text": "MessageSquareTextIcon",
  "messages-square": "MessagesSquareIcon",
  mic: "MicIcon",
  "package-search": "PackageSearchIcon",
  paperclip: "PaperclipIcon",
  "panels-top-left": "PanelsTopLeftIcon",
  pause: "PauseIcon",
  pencil: "PencilIcon",
  play: "PlayIcon",
  plug: "PlugIcon",
  plus: "PlusIcon",
  search: "SearchIcon",
  server: "ServerIcon",
  "server-cog": "ServerCogIcon",
  settings: "SettingsIcon",
  "share-2": "Share2Icon",
  shrink: "ShrinkIcon",
  sparkles: "SparklesIcon",
  square: "SquareIcon",
  "square-terminal": "SquareTerminalIcon",
  target: "TargetIcon",
  terminal: "TerminalIcon",
  "thumbs-down": "ThumbsDownIcon",
  "thumbs-up": "ThumbsUpIcon",
  "trash-2": "Trash2Icon",
  "triangle-alert": "TriangleAlertIcon",
  wrench: "WrenchIcon",
  x: "XIcon",
  zap: "ZapIcon",
  pin: "PinIcon",
  "pin-off": "PinOffIcon",
  ellipsis: "EllipsisIcon",
  "grip-vertical": "GripVerticalIcon",
  "audio-lines": "AudioLinesIcon",
  "list-restart": "ListRestartIcon",
};

const out: Record<string, Array<[string, Record<string, string | number>]>> = {};
for (const [name, exportName] of Object.entries(ICONS)) {
  const icon = lucide[exportName];
  const node = icon?.render?.({}, null)?.props?.iconNode;
  if (!node) throw new Error(`lucide-react has no ${exportName}`);
  out[name] = node.map(([tag, attrs]) => {
    const { key: _key, ...rest } = attrs;
    return [tag, rest];
  });
}

const target = join(
  import.meta.dir,
  "../packages/react-native/src/timeline/icon-nodes.generated.ts",
);
writeFileSync(
  target,
  `// GENERATED by scripts/generate-native-icons.ts from lucide-react. Do not edit.\n` +
    `export const iconNodes = ${JSON.stringify(out, null, 2)} as const;\n\n` +
    `export type NativeIconName = keyof typeof iconNodes;\n`,
);
console.log(`wrote ${Object.keys(out).length} icons to ${target}`);
