import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const result = await Bun.build({
  entrypoints: [resolve(root, "packages/sdk/src/site-browser-entry.ts")],
  target: "browser",
  format: "iife",
  minify: true,
});
if (!result.success) throw new AggregateError(result.logs, "Site runtime build failed");
const script = await result.outputs[0]!.text();
const source =
  "// Generated by scripts/generate-site-browser-runtime.ts. Do not edit.\n" +
  "export const SITE_BROWSER_RUNTIME = " +
  JSON.stringify(script) +
  ";\n";
const destination = resolve(root, "packages/sdk/src/site-browser-runtime.gen.ts");
if (process.argv.includes("--check")) {
  if ((await Bun.file(destination).text()) !== source)
    throw new Error("Regenerate the Site browser runtime");
} else {
  await Bun.write(destination, source);
}
