import { chmod, mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { nkeys } from "@opengeni/events";

const encoder = new TextEncoder();

type DevelopmentNatsConfig = {
  accountSeed: string;
  accountPublicKey: string;
  accountName: string;
  calloutUser: string;
  calloutPassword: string;
  controlUser: string;
  controlPassword: string;
};

function required(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function quoted(value: string): string {
  return JSON.stringify(value);
}

function load(): DevelopmentNatsConfig {
  const accountSeed = required("OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_SEED");
  const accountPublicKey = nkeys.fromSeed(encoder.encode(accountSeed)).getPublicKey();
  const configuredPublicKey = process.env.OPENGENI_SELFHOSTED_NATS_CALLOUT_PUBLIC_KEY?.trim();
  if (configuredPublicKey && configuredPublicKey !== accountPublicKey) {
    throw new Error("NATS auth-callout public key does not match its account seed");
  }
  return {
    accountSeed,
    accountPublicKey,
    accountName: required("OPENGENI_SELFHOSTED_NATS_CALLOUT_ACCOUNT_NAME"),
    calloutUser: required("OPENGENI_SELFHOSTED_NATS_CALLOUT_USER"),
    calloutPassword: required("OPENGENI_SELFHOSTED_NATS_CALLOUT_PASSWORD"),
    controlUser: required("OPENGENI_SELFHOSTED_NATS_CONTROL_USER"),
    controlPassword: required("OPENGENI_SELFHOSTED_NATS_CONTROL_PASSWORD"),
  };
}

function render(config: DevelopmentNatsConfig): string {
  return `# Generated by scripts/dev-stack.sh. Contains local-only credentials; do not commit.
port: 4222
http: 8222

accounts {
  ${quoted(config.accountName)}: {
    users: [
      { user: ${quoted(config.controlUser)}, password: ${quoted(config.controlPassword)} }
      { user: ${quoted(config.calloutUser)}, password: ${quoted(config.calloutPassword)} }
    ]
  }
  SYS: {}
}
system_account: SYS

authorization {
  auth_callout {
    issuer: ${config.accountPublicKey}
    auth_users: [ ${quoted(config.calloutUser)}, ${quoted(config.controlUser)} ]
    account: ${quoted(config.accountName)}
  }
}
`;
}

async function main(): Promise<void> {
  const outputIndex = process.argv.indexOf("--output");
  const outputValue = outputIndex >= 0 ? process.argv[outputIndex + 1] : undefined;
  if (!outputValue || process.argv.length !== 4) {
    throw new Error("usage: prepare-development-nats-config.ts --output <path>");
  }
  const output = resolve(outputValue);
  await mkdir(dirname(output), { recursive: true, mode: 0o700 });
  const temporary = `${output}.${crypto.randomUUID()}.tmp`;
  await writeFile(temporary, render(load()), { mode: 0o600, flag: "wx" });
  await rename(temporary, output);
  await chmod(output, 0o600);
  process.stdout.write(`${output}\n`);
}

await main();
