import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const source = join(root, ".agents/skills/opengeni-client");
const destination = join(root, "packages/runtime/src/bundled_default_skills/opengeni-client");
/** Public docs mirror, so agents can read the Skill from docs.opengeni.ai without git. */
const docsMirror = join(root, "docs-site/reference/opengeni-client-skill.mdx");

async function files(directory: string): Promise<Map<string, string>> {
  const result = new Map<string, string>();
  async function visit(path: string): Promise<void> {
    const entries = await readdir(path, { withFileTypes: true });
    entries.sort((a, b) => a.name.localeCompare(b.name));
    for (const entry of entries) {
      const child = join(path, entry.name);
      if (entry.isDirectory()) await visit(child);
      else if (entry.isFile())
        result.set(relative(directory, child).replaceAll("\\", "/"), await readFile(child, "utf8"));
      else throw new Error(`Unsupported client Skill entry: ${child}`);
    }
  }
  await visit(directory);
  return result;
}

/** Fence longer than any backtick run in the text, so nested code blocks survive. */
function fence(text: string): string {
  const longest = Math.max(0, ...[...text.matchAll(/`+/g)].map((match) => match[0].length));
  return "`".repeat(Math.max(3, longest + 1));
}

/** One MDX page holding every Skill file verbatim inside fenced blocks. */
export function renderClientSkillDocsPage(skill: Map<string, string>): string {
  const order = [...skill.keys()].sort((a, b) =>
    a === "SKILL.md" ? -1 : b === "SKILL.md" ? 1 : a.localeCompare(b),
  );
  const sections = order.map((path) => {
    const text = skill.get(path)!;
    const marker = fence(text);
    const language = path.endsWith(".md") ? "markdown" : path.endsWith(".yaml") ? "yaml" : "text";
    const body = text.endsWith("\n") ? text : `${text}\n`;
    return `## \`${path}\`\n\n${marker}${language}\n${body}${marker}\n`;
  });
  return [
    "---",
    'title: "opengeni-client skill (full text)"',
    'sidebarTitle: "Skill full text"',
    'description: "The complete opengeni-client integration Skill, mirrored from the repository for agents that cannot use git."',
    'icon: "file-code"',
    "---",
    "",
    "{/* Generated by `bun run sync:client-skill` from .agents/skills/opengeni-client. Do not edit. */}",
    "",
    "This page mirrors every file of the [`opengeni-client`](https://github.com/Cloudgeni-ai/opengeni/tree/main/.agents/skills/opengeni-client) Skill verbatim. To install it, see [For AI agents](/reference/for-ai-agents). Agents can fetch this page as Markdown by appending `.md` to its URL, then write each section to the path in its heading, relative to a directory named `opengeni-client`.",
    "",
    ...sections,
  ].join("\n");
}

async function checkDocsMirror(expected: Map<string, string>): Promise<void> {
  const actual = await readFile(docsMirror, "utf8").catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return null;
    throw error;
  });
  if (actual !== renderClientSkillDocsPage(expected))
    throw new Error(
      "Docs-site client Skill mirror is missing or stale; run bun run sync:client-skill",
    );
}

/** The repository guide is the sole authored copy. Runtime assets and the docs mirror are generated. */
export async function checkClientSkill(): Promise<void> {
  const expected = await files(source);
  await checkDocsMirror(expected);
  let actual: Map<string, string>;
  try {
    actual = await files(destination);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    throw new Error("Bundled client Skill is missing; run bun run sync:client-skill", {
      cause: error,
    });
  }
  if (
    expected.size !== actual.size ||
    [...expected].some(([path, text]) => actual.get(path) !== text)
  )
    throw new Error("Bundled client Skill is stale; run bun run sync:client-skill");
}

export async function syncClientSkill(): Promise<void> {
  const expected = await files(source);
  // Only this generated directory is replaced, including obsolete references.
  await rm(destination, { recursive: true, force: true });
  for (const [path, text] of expected) {
    const target = join(destination, path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, text);
  }
  await writeFile(docsMirror, renderClientSkillDocsPage(expected));
}

if (import.meta.main) {
  if (process.argv.slice(2).some((arg) => arg !== "--check"))
    throw new Error("Usage: bun scripts/sync-client-skill.ts [--check]");
  if (process.argv.includes("--check")) await checkClientSkill();
  else await syncClientSkill();
}
