import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { parseDocument } from "yaml";

const root = fileURLToPath(new URL("..", import.meta.url));
const canonical = join(root, ".agents/skills/opengeni-client");
const destination = join(root, "packages/core/src/domain/product-integration-skill.gen.ts");
export const packSkillDescription =
  "Design, implement, verify, and hand off a tenant-safe OpenGeni product integration while adapting to the customer's architecture, UI, data APIs, and desired delivery autonomy. Select only for an implementation session; installation alone does not expose it to other agents.";

function entrypoint(source: string): string {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(source);
  if (!match) throw new Error("Client Skill requires YAML frontmatter");
  const header = parseDocument(match[1]!);
  if (header.errors.length || header.get("name") !== "opengeni-client") {
    throw new Error("Client Skill frontmatter is invalid");
  }
  // The only Pack-specific wrapper differences: install identity, description,
  // and the explicit activation notice. All implementation recipes are shared.
  header.set("name", "opengeni-product-integration");
  header.set("description", packSkillDescription);
  return `---\n${header.toString()}---\n\nThis implementation Skill is inactive until explicitly selected for an implementation session. Never attach it to customer-facing runtime sessions.\n\n${source.slice(match[0].length)}`;
}

export async function productIntegrationSkillSource(): Promise<string> {
  const files: Array<{ path: string; content: string }> = [];
  async function visit(directory: string): Promise<void> {
    const entries = await readdir(directory, { withFileTypes: true });
    entries.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    for (const entry of entries) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) await visit(path);
      else if (entry.isFile()) {
        const name = relative(canonical, path).replaceAll("\\", "/");
        const source = await readFile(path, "utf8");
        files.push({ path: name, content: name === "SKILL.md" ? entrypoint(source) : source });
      } else throw new Error(`Unsupported canonical Skill entry: ${entry.name}`);
    }
  }
  await visit(canonical);
  return `// Generated by scripts/sync-product-integration-skill.ts. Do not edit.\nexport const productIntegrationSkillDescription = ${JSON.stringify(packSkillDescription)};\nexport const productIntegrationSkillFiles = ${JSON.stringify(files, null, 2)};\n`;
}

export async function checkProductIntegrationSkill(): Promise<void> {
  if ((await readFile(destination, "utf8")) !== (await productIntegrationSkillSource())) {
    throw new Error(
      "Product Integration Skill is stale; run bun scripts/sync-product-integration-skill.ts",
    );
  }
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.some((arg) => !["--check", "--import-existing"].includes(arg))) {
    throw new Error("Usage: sync-product-integration-skill.ts [--check | --import-existing]");
  }
  if (args.includes("--import-existing")) {
    // One-time lossless consolidation of previously hand-authored Pack recipes.
    // Exclusive writes refuse to overwrite any canonical guide.
    const { OPENGENI_PRODUCT_INTEGRATION_SKILL } =
      await import("../packages/core/src/domain/product-integration-pack");
    for (const file of OPENGENI_PRODUCT_INTEGRATION_SKILL.files) {
      const path = file.path === "SKILL.md" ? "references/implementation-overview.md" : file.path;
      const target = join(canonical, path);
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, file.content, { flag: "wx" });
    }
  }
  if (args.includes("--check")) await checkProductIntegrationSkill();
  else await writeFile(destination, await productIntegrationSkillSource());
}
