import { describe, expect, test } from "bun:test";

import { MINIMUM_RAW_HEADROOM_BYTES } from "./web-bundle-budget-policy";
import {
  KIB,
  WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_GZIP_BUDGET,
  WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_GZIP_MEASUREMENT,
  WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_BUDGET,
  WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_MEASUREMENT,
} from "./web-bundle-budget-workbench-credit-drain";

describe("workbench credit-drain hang-fix web bundle budget", () => {
  test("retains the hang-fix Files/Terminal overlay envelope", () => {
    expect(WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_MEASUREMENT).toBe(2_292_551);
    expect(WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_BUDGET).toBe(2240 * KIB);
    expect(
      WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_BUDGET -
        WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_MEASUREMENT,
    ).toBe(1_209);
    expect(
      WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_BUDGET -
        WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_RAW_MEASUREMENT,
    ).toBeGreaterThanOrEqual(MINIMUM_RAW_HEADROOM_BYTES);
    expect(WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_GZIP_MEASUREMENT).toBe(640_121);
    expect(WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_GZIP_BUDGET).toBe(627 * KIB);
    expect(
      WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_GZIP_BUDGET -
        WORKBENCH_CREDIT_DRAIN_HANGS_BROWSER_GZIP_MEASUREMENT,
    ).toBe(1_927);
  });
});
