import { describe, expect, test } from "bun:test";
import type { RetainedArtifactReference } from "@opengeni/sdk";
import { createWorkspaceRetainedArtifactLoader } from "./retained-artifact-loader";

const artifact: RetainedArtifactReference = {
  available: true,
  artifactId: "33333333-3333-4333-8333-333333333333",
  kind: "generated_image",
  contentType: "image/png",
  originalBytes: 1024,
  sha256: "c".repeat(64),
  retainedAt: "2026-08-08T00:00:00.000Z",
  dimensions: { width: 1024, height: 1024 },
  retention: { policy: "workspace_file", expiresAt: null },
  retrieval: {
    method: "GET",
    path: "/v1/workspaces/workspace-a/artifacts/33333333-3333-4333-8333-333333333333/content",
    acceptRanges: "bytes",
    maxRangeBytes: 1024 * 1024,
  },
};

describe("workspace retained artifact loader", () => {
  test("mints a signed URL instead of downloading generated bytes into browser RAM", async () => {
    const calls: Array<{ workspaceId: string; artifact: RetainedArtifactReference }> = [];
    const loader = createWorkspaceRetainedArtifactLoader(
      {
        createRetainedArtifactDownloadUrl: async (workspaceId, received) => {
          calls.push({ workspaceId, artifact: received });
          return {
            url: "https://objects.example/generated.png?signature=test",
            expiresAt: "2026-08-08T00:15:00.000Z",
          };
        },
      },
      "workspace-a",
    );

    const result = await loader(artifact, new AbortController().signal);
    expect(result).toEqual({ url: "https://objects.example/generated.png?signature=test" });
    expect(calls).toEqual([{ workspaceId: "workspace-a", artifact }]);
  });
});
