/** These migrations extend the post-0299 lifecycle and accepted-work ledgers.
 * Historical cutover fixtures must withhold and replay this entire ordered tail. */
export const embeddingMigrationTail = [
  "0432_organization_scoped_external_workspaces.sql",
  "0433_durable_connect_attempts.sql",
  "0434_external_identity_provisioning.sql",
  "0435_external_workspace_member_removal.sql",
  "0436_external_identity_membership_lifecycle.sql",
  "0437_external_owning_user_authority.sql",
  "0438_host_mcp_binding_registry.sql",
  "0439_host_mcp_delegations.sql",
  "0440_host_mcp_turn_authorities.sql",
  "0441_host_mcp_causal_continuation.sql",
  "0442_host_mcp_task_authorities.sql",
  "0443_host_mcp_child_authority.sql",
  "0444_external_identity_link_lifecycle.sql",
  "0445_external_identity_link_work.sql",
  "0446_external_link_preview_and_permission_ceiling.sql",
  "0447_external_link_scheduled_origin.sql",
  "0448_host_mcp_native_owner.sql",
  "0449_connect_origin_authority.sql",
  "0450_external_link_inventory_labels.sql",
  "0451_social_connection_versions.sql",
  "0452_canonical_session_scope_subject.sql",
];
